/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

//import dev.skyherobrine.app.controllers.dashboardui.thongKe.thongKeDoanhThuController;

import javax.swing.*;

/**
 *
 * @author Virtue Nguyen
 */
public class FormBaoCaoDoanhThuCuaHang extends JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public FormBaoCaoDoanhThuCuaHang() {
        initComponents();

//        thongKeDoanhThuController controller = new thongKeDoanhThuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
//     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBGThongTinCaNhan = new JPanel();
        pnBieuDoTHongKeDoanhThu = new JPanel();
        pnBoLocDoanhTHuCuaHang = new JPanel();
        pnKetQuaDoanhThu = new JPanel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        txtBaoCaoDoanhThu = new JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBieuDoTHongKeDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        pnBieuDoTHongKeDoanhThu.setBorder(BorderFactory.createTitledBorder(null, "Biểu đồ thống kê doanh thu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        GroupLayout pnBieuDoTHongKeDoanhThuLayout = new GroupLayout(pnBieuDoTHongKeDoanhThu);
        pnBieuDoTHongKeDoanhThu.setLayout(pnBieuDoTHongKeDoanhThuLayout);
        pnBieuDoTHongKeDoanhThuLayout.setHorizontalGroup(
            pnBieuDoTHongKeDoanhThuLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
        );
        pnBieuDoTHongKeDoanhThuLayout.setVerticalGroup(
            pnBieuDoTHongKeDoanhThuLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnBoLocDoanhTHuCuaHang.setBackground(new java.awt.Color(255, 255, 255));
        pnBoLocDoanhTHuCuaHang.setBorder(BorderFactory.createTitledBorder(null, "Bộ lọc doanh thu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        GroupLayout pnBoLocDoanhTHuCuaHangLayout = new GroupLayout(pnBoLocDoanhTHuCuaHang);
        pnBoLocDoanhTHuCuaHang.setLayout(pnBoLocDoanhTHuCuaHangLayout);
        pnBoLocDoanhTHuCuaHangLayout.setHorizontalGroup(
            pnBoLocDoanhTHuCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 1641, Short.MAX_VALUE)
        );
        pnBoLocDoanhTHuCuaHangLayout.setVerticalGroup(
            pnBoLocDoanhTHuCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        pnKetQuaDoanhThu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel5.setText("Kết quả thống kê");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Doanh thu:");

        txtBaoCaoDoanhThu.setText("Chua có dữ liệu");
        txtBaoCaoDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaoCaoDoanhThuActionPerformed(evt);
            }
        });

        GroupLayout pnKetQuaDoanhThuLayout = new GroupLayout(pnKetQuaDoanhThu);
        pnKetQuaDoanhThu.setLayout(pnKetQuaDoanhThuLayout);
        pnKetQuaDoanhThuLayout.setHorizontalGroup(
            pnKetQuaDoanhThuLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnKetQuaDoanhThuLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(126, 126, 126))
            .addGroup(pnKetQuaDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBaoCaoDoanhThu)
                .addGap(24, 24, 24))
        );
        pnKetQuaDoanhThuLayout.setVerticalGroup(
            pnKetQuaDoanhThuLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnKetQuaDoanhThuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnKetQuaDoanhThuLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaoCaoDoanhThu))
                .addContainerGap(707, Short.MAX_VALUE))
        );

        GroupLayout pnBGThongTinCaNhanLayout = new GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBoLocDoanhTHuCuaHang, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnBieuDoTHongKeDoanhThu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnKetQuaDoanhThu, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnBoLocDoanhTHuCuaHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(pnBieuDoTHongKeDoanhThu, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnKetQuaDoanhThu, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBaoCaoDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaoCaoDoanhThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaoCaoDoanhThuActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel pnBGThongTinCaNhan;
    private JPanel pnBieuDoTHongKeDoanhThu;
    private JPanel pnBoLocDoanhTHuCuaHang;
    private JPanel pnKetQuaDoanhThu;
    private JTextField txtBaoCaoDoanhThu;
    // End of variables declaration//GEN-END:variables
    public JPanel getPnBieuDoTHongKeDoanhThu() {
        return pnBieuDoTHongKeDoanhThu;
    }
    public JTextField getTxtBaoCaoDoanhThu() {
        return txtBaoCaoDoanhThu;
    }
}
