/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JYearChooser;
import dev.skyherobrine.app.controllers.dashboardui.person.KhachHangController;
import dev.skyherobrine.app.daos.KhachHangDAO;
//import dev.skyherobrine.app.controllers.dashboardui.person.KhachHangController;

import javax.swing.*;

/**
 *
 * @author Virtue Nguyen
 */
public class FrmKhachHang extends JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public FrmKhachHang() {
        initComponents();
//        controller.loaddsKhachHang();
//        controller.loadComboBoxPhanThongTinNV();
//        controller.loadComboBoxPhanTimKiem();
//        tbDanhSachKhachHang.addMouseListener(controller);
        
//
       

        KhachHangController controller = new KhachHangController(this);
        
        tbDanhSachKhachHang.addMouseListener(controller);
        btnThemKhachHang.addActionListener(controller);
        btnSuaKhachHang.addActionListener(controller);
        btnXuatFile.addActionListener(controller);
        cbTkGioiTinhKhachHang.addActionListener(controller);
        jDateChooserTkNgaySinh.addPropertyChangeListener(controller);
        jDateChooserTuNgayLocDanhSach.addPropertyChangeListener(controller);
        jDateChooserDenNgayLocDanhSachFile.addPropertyChangeListener(controller);
        cbThangLoc.addPropertyChangeListener(controller);
        jYearChooserNam.addPropertyChangeListener(controller);
        btnLocDanhSach.addActionListener(controller);
        btnLamMoiLoc.addActionListener(controller);
        txtTuKhoaTimKiem.addKeyListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBGThongTinCaNhan = new JPanel();
        pnThongTinKhachHang = new JPanel();
        lbMaNhanVien = new JLabel();
        txtMaKhachHang = new JTextField();
        lbHoTenNhanVien = new JLabel();
        txtHoTenKhachHang = new JTextField();
        lbGIoiTinhNhanVien = new JLabel();
        lbSoDienThoaiNhanVien = new JLabel();
        txtSoDienThoaiKhachHang = new JTextField();
        lbEmail = new JLabel();
        txtDiemTichLuy = new JTextField();
        lbNgaySinhNhanVien = new JLabel();
        btnSuaKhachHang = new JButton();
        btnThemKhachHang = new JButton();
        btnXuatFile = new JButton();
        cbGioiTinh = new JComboBox<>();
        jDateChooserNgaySinh = new JDateChooser();
        pnDanhSachKhachHang = new JPanel();
        spDanhSachKhachHang = new JScrollPane();
        tbDanhSachKhachHang = new JTable();
        pnTimKiemKhachHang = new JPanel();
        cbTkGioiTinhKhachHang = new JComboBox<>();
        lbTkTenKhachHang = new JLabel();
        txtTuKhoaTimKiem = new JTextField();
        jLabel1 = new JLabel();
        jDateChooserTkNgaySinh = new JDateChooser();
        pnLocDanhSachXuatFile = new JPanel();
        jYearChooserNam = new JYearChooser();
        jDateChooserDenNgayLocDanhSachFile = new JDateChooser();
        jDateChooserTuNgayLocDanhSach = new JDateChooser();
        lblTuNgay = new JLabel();
        lblDenNgay = new JLabel();
        lblThangLoc = new JLabel();
        lblNamLoc = new JLabel();
        btnLocDanhSach = new JButton();
        btnLamMoiLoc = new JButton();
        lblLocTheoNamThang = new JLabel();
        lblTieuDeLocTheoNgay = new JLabel();
        cbThangLoc = new JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnThongTinKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinKhachHang.setBorder(BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        pnThongTinKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lbMaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaNhanVien.setHorizontalAlignment(SwingConstants.RIGHT);
        lbMaNhanVien.setText("Mã khách hàng:");

        txtMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaKhachHang.setEnabled(false);
        txtMaKhachHang.setPreferredSize(new java.awt.Dimension(64, 25));

        lbHoTenNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHoTenNhanVien.setHorizontalAlignment(SwingConstants.RIGHT);
        lbHoTenNhanVien.setText("Họ tên:");

        txtHoTenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHoTenKhachHang.setEnabled(false);
        txtHoTenKhachHang.setPreferredSize(new java.awt.Dimension(64, 25));

        lbGIoiTinhNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGIoiTinhNhanVien.setText("Giới tính:");

        lbSoDienThoaiNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSoDienThoaiNhanVien.setText("Số điện thoại:");

        txtSoDienThoaiKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoDienThoaiKhachHang.setEnabled(false);
        txtSoDienThoaiKhachHang.setPreferredSize(new java.awt.Dimension(79, 33));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEmail.setText("Điểm tích luỹ:");

        txtDiemTichLuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiemTichLuy.setEnabled(false);

        lbNgaySinhNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgaySinhNhanVien.setText("Ngày Sinh:");

        btnSuaKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuaKhachHang.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/edit.png"))); // NOI18N
        btnSuaKhachHang.setText("Sửa khách hàng");

        btnThemKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemKhachHang.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/plus.png"))); // NOI18N
        btnThemKhachHang.setText("Thêm khách hàng");

        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXuatFile.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/export.png"))); // NOI18N
        btnXuatFile.setText("Xuất danh sách");

        cbGioiTinh.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGioiTinh.setEnabled(false);

        jDateChooserNgaySinh.setEnabled(false);

        GroupLayout pnThongTinKhachHangLayout = new GroupLayout(pnThongTinKhachHang);
        pnThongTinKhachHang.setLayout(pnThongTinKhachHangLayout);
        pnThongTinKhachHangLayout.setHorizontalGroup(
            pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSoDienThoaiNhanVien)
                                    .addComponent(lbNgaySinhNhanVien))
                                .addGap(25, 25, 25)
                                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoDienThoaiKhachHang, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserNgaySinh, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(lbMaNhanVien)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaKhachHang, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnThemKhachHang)))
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGIoiTinhNhanVien)
                                    .addComponent(lbHoTenNhanVien))
                                .addGap(45, 45, 45)
                                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGioiTinh, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoTenKhachHang, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                                .addComponent(lbEmail)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemTichLuy, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(96, Short.MAX_VALUE))
                    .addGroup(pnThongTinKhachHangLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSuaKhachHang)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatFile)
                        .addGap(137, 137, 137))))
        );
        pnThongTinKhachHangLayout.setVerticalGroup(
            pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnThongTinKhachHangLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNhanVien, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhachHang, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTenKhachHang, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTenNhanVien, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGIoiTinhNhanVien, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoDienThoaiKhachHang, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoDienThoaiNhanVien, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGioiTinh, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNgaySinhNhanVien, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiemTichLuy, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbEmail))
                    .addComponent(jDateChooserNgaySinh, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addGroup(pnThongTinKhachHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKhachHang, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatFile, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaKhachHang, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pnDanhSachKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachKhachHang.setBorder(BorderFactory.createTitledBorder(null, "Danh Sách khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        pnDanhSachKhachHang.setLayout(new java.awt.BorderLayout());

        tbDanhSachKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Số điện thoại", "Giới tính", "Ngày sinh"
            }
        ));
        spDanhSachKhachHang.setViewportView(tbDanhSachKhachHang);

        pnDanhSachKhachHang.add(spDanhSachKhachHang, java.awt.BorderLayout.CENTER);

        pnTimKiemKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnTimKiemKhachHang.setBorder(BorderFactory.createTitledBorder(null, "Tìm Kiếm khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        cbTkGioiTinhKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkGioiTinhKhachHang.setModel(new DefaultComboBoxModel<>(new String[] { "Giới tính", "Nam", "Nữ", "Gay", "Les", " " }));

        lbTkTenKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTkTenKhachHang.setText("Từ khoá tìm kiếm:");

        txtTuKhoaTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ngày sinh:");

        GroupLayout pnTimKiemKhachHangLayout = new GroupLayout(pnTimKiemKhachHang);
        pnTimKiemKhachHang.setLayout(pnTimKiemKhachHangLayout);
        pnTimKiemKhachHangLayout.setHorizontalGroup(
            pnTimKiemKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemKhachHangLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(cbTkGioiTinhKhachHang, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTkNgaySinh, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189)
                .addComponent(lbTkTenKhachHang)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoaTimKiem, GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(137, 137, 137))
        );
        pnTimKiemKhachHangLayout.setVerticalGroup(
            pnTimKiemKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnTimKiemKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemKhachHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTkGioiTinhKhachHang)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserTkNgaySinh, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, pnTimKiemKhachHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(txtTuKhoaTimKiem)
                .addComponent(lbTkTenKhachHang, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        );

        pnLocDanhSachXuatFile.setBackground(new java.awt.Color(255, 255, 255));
        pnLocDanhSachXuatFile.setBorder(BorderFactory.createTitledBorder(null, "Lọc danh sách xuất file", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        jYearChooserNam.setEnabled(false);

        jDateChooserDenNgayLocDanhSachFile.setEnabled(false);

        jDateChooserTuNgayLocDanhSach.setEnabled(false);

        lblTuNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTuNgay.setText("Từ ngày:");

        lblDenNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDenNgay.setText("Đến ngày:");

        lblThangLoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThangLoc.setText("Tháng:");

        lblNamLoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamLoc.setText("Năm:");

        btnLocDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLocDanhSach.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/magnifying-glass.png"))); // NOI18N
        btnLocDanhSach.setText("Lọc danh sách");
        btnLocDanhSach.setEnabled(false);

        btnLamMoiLoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLamMoiLoc.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/cleaning.png"))); // NOI18N
        btnLamMoiLoc.setText("Làm mới");
        btnLamMoiLoc.setEnabled(false);
        btnLamMoiLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiLocActionPerformed(evt);
            }
        });

        lblLocTheoNamThang.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblLocTheoNamThang.setText("Hoặc lọc theo Năm và Tháng");

        lblTieuDeLocTheoNgay.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTieuDeLocTheoNgay.setText("Lọc theo ngày(từ ngày .. đến ngày ..)");

        cbThangLoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbThangLoc.setModel(new DefaultComboBoxModel<>(new String[] { "--Select--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        cbThangLoc.setEnabled(false);

        GroupLayout pnLocDanhSachXuatFileLayout = new GroupLayout(pnLocDanhSachXuatFile);
        pnLocDanhSachXuatFile.setLayout(pnLocDanhSachXuatFileLayout);
        pnLocDanhSachXuatFileLayout.setHorizontalGroup(
            pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnLocDanhSachXuatFileLayout.createSequentialGroup()
                .addGroup(pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnLocDanhSachXuatFileLayout.createSequentialGroup()
                        .addGroup(pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lblTuNgay)
                            .addComponent(lblDenNgay))
                        .addGap(18, 18, 18)
                        .addGroup(pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserDenNgayLocDanhSachFile, GroupLayout.PREFERRED_SIZE, 224, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserTuNgayLocDanhSach, GroupLayout.PREFERRED_SIZE, 224, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTieuDeLocTheoNgay, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocTheoNamThang, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, pnLocDanhSachXuatFileLayout.createSequentialGroup()
                .addComponent(lblNamLoc, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jYearChooserNam, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblThangLoc, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbThangLoc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(GroupLayout.Alignment.TRAILING, pnLocDanhSachXuatFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLocDanhSach)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLamMoiLoc, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnLocDanhSachXuatFileLayout.setVerticalGroup(
            pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnLocDanhSachXuatFileLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTieuDeLocTheoNgay)
                .addGap(18, 18, 18)
                .addGroup(pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTuNgay, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserTuNgayLocDanhSach, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDenNgay, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserDenNgayLocDanhSachFile, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLocTheoNamThang)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblThangLoc, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbThangLoc, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jYearChooserNam, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamLoc, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnLocDanhSachXuatFileLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLocDanhSach)
                    .addComponent(btnLamMoiLoc))
                .addGap(15, 15, 15))
        );

        GroupLayout pnBGThongTinCaNhanLayout = new GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnTimKiemKhachHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDanhSachKhachHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnThongTinKhachHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnLocDanhSachXuatFile, GroupLayout.PREFERRED_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnDanhSachKhachHang, GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiemKhachHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnThongTinKhachHang, GroupLayout.PREFERRED_SIZE, 343, GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnLocDanhSachXuatFile, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiLocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnLamMoiLoc;
    private JButton btnLocDanhSach;
    private JButton btnSuaKhachHang;
    private JButton btnThemKhachHang;
    private JButton btnXuatFile;
    private JComboBox<String> cbGioiTinh;
    private JComboBox<String> cbThangLoc;
    private JComboBox<String> cbTkGioiTinhKhachHang;
    private JDateChooser jDateChooserDenNgayLocDanhSachFile;
    private JDateChooser jDateChooserNgaySinh;
    private JDateChooser jDateChooserTkNgaySinh;
    private JDateChooser jDateChooserTuNgayLocDanhSach;
    private JLabel jLabel1;
    private JYearChooser jYearChooserNam;
    private JLabel lbEmail;
    private JLabel lbGIoiTinhNhanVien;
    private JLabel lbHoTenNhanVien;
    private JLabel lbMaNhanVien;
    private JLabel lbNgaySinhNhanVien;
    private JLabel lbSoDienThoaiNhanVien;
    private JLabel lbTkTenKhachHang;
    private JLabel lblDenNgay;
    private JLabel lblLocTheoNamThang;
    private JLabel lblNamLoc;
    private JLabel lblThangLoc;
    private JLabel lblTieuDeLocTheoNgay;
    private JLabel lblTuNgay;
    private JPanel pnBGThongTinCaNhan;
    private JPanel pnDanhSachKhachHang;
    private JPanel pnLocDanhSachXuatFile;
    private JPanel pnThongTinKhachHang;
    private JPanel pnTimKiemKhachHang;
    private JScrollPane spDanhSachKhachHang;
    private JTable tbDanhSachKhachHang;
    private JTextField txtDiemTichLuy;
    private JTextField txtHoTenKhachHang;
    private JTextField txtMaKhachHang;
    private JTextField txtSoDienThoaiKhachHang;
    private JTextField txtTuKhoaTimKiem;
    // End of variables declaration//GEN-END:variables

    public JTable getTbDanhSachKhachHang() {
        return tbDanhSachKhachHang;
    }
    public JButton getButtonThemKhachHang(){return btnThemKhachHang;}
    public JButton getButtonSuaKhachHang(){return btnSuaKhachHang;}
    public JButton getButtonXoaKhachHang(){return btnXuatFile;}
    public JTextField getTxtMaKhachHang(){return txtMaKhachHang;}
    public JTextField getTxtSoDienThoaiKhachHang(){return txtSoDienThoaiKhachHang;}
    public JDateChooser getjDateChooserNgaySinhKhachHang(){return jDateChooserNgaySinh;}
    public JTextField getTxtHoTenKhachHang(){return txtHoTenKhachHang;}
    public JComboBox getCbGioiTinh(){return  cbGioiTinh;}
    public JTextField getTxtDiemTichLuy(){return txtDiemTichLuy;}
    public JComboBox getCbTkGioiTinh(){return cbTkGioiTinhKhachHang;}
    public JTextField getTxtTuKhoaTimKiem(){return txtTuKhoaTimKiem;}
    public JDateChooser getjDateChooserTkNgaySinh(){return jDateChooserTkNgaySinh;}
    public JDateChooser getjDateChooserTuNgayLocDanhSach(){return jDateChooserTuNgayLocDanhSach;}
    public JDateChooser getjDateChooserDenNgayLocDanhSachFile(){return jDateChooserDenNgayLocDanhSachFile;}
    public JComboBox<String> getCbThangLoc(){return cbThangLoc;}
    public JYearChooser getjYearChooserNam(){return jYearChooserNam;}
    public JButton getBtnLocDanhSach(){return btnLocDanhSach;}
    public JButton getBtnLamMoiLoc(){return btnLamMoiLoc;}
}
