/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

//import dev.skyherobrine.app.controllers.dashboardui.mainDashboard.LapHoaDonController;
import dev.skyherobrine.app.controllers.dashboardui.mainDashboard.LapHoaDonController;
import dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellEditor;
import dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellRender;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;


/**
 *
 * @author Virtue Nguyen
 */
public class LapHoaDon extends JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public LapHoaDon() {
        initComponents();
        LapHoaDonController controller = new LapHoaDonController(this);
        tbDanhSachCacSanPhamTrongGioHang.getColumnModel().getColumn(7).setCellRenderer(new TableActionCellRender());
        tbDanhSachCacSanPhamTrongGioHang.getColumnModel().getColumn(7).setCellEditor(new TableActionCellEditor(controller));
        tbHoaDonLuuTam.getColumnModel().getColumn(3).setCellEditor(new dev.skyherobrine.app.views.dashboard.component.nutDuyetVaNutXoaDongTb.TableActionCellEditor1(controller));
        tbHoaDonLuuTam.getColumnModel().getColumn(3).setCellRenderer(new dev.skyherobrine.app.views.dashboard.component.nutDuyetVaNutXoaDongTb.TableActionCellRender1());
        txtMaHoaDon.setEnabled(false);
        txtNgayLapHoaDon.setEnabled(false);
        txtGiamGia.setEnabled(false);
        txtTienDu.setEnabled(false);
        txtTienKhachDua.setEnabled(true);
        listProduct.addKeyListener(controller);
        listKhachHang.addKeyListener(controller);
        txtSoDienThoaiKh.addKeyListener(controller);
        txtTimKiemSanPham.addKeyListener(controller);
        menuProduct.add(panel2);
        menuKhachHang.add(pnTTKH);
        tbDanhSachCacSanPhamTrongGioHang.getModel().addTableModelListener(controller);
        btnLuuTam.addActionListener(controller);
        jCheckBox1.addActionListener(controller);
        txtTienKhachDua.addKeyListener(controller);
        btnLapHoaDon.addActionListener(controller);
        txtTimKiemHoaDonLuuTam.addKeyListener(controller);
        txtTienKhachDua.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jScrollPane1 = new JScrollPane();
        listProduct = new JList<>();
        menuProduct = new JPopupMenu();
        pnTTKH = new java.awt.Panel();
        jScrollPane2 = new JScrollPane();
        listKhachHang = new JList<>();
        menuKhachHang = new JPopupMenu();
        pnBGLapHoaDon = new JPanel();
        pnTraiLapHoaDon = new JPanel();
        pnPhaiTrenLapHoaDon = new JPanel();
        txtTimKiemSanPham = new JTextField();
        jPanel2 = new JPanel();
        spDanhSachCacSanPhamTrongGioHang = new JScrollPane();
        tbDanhSachCacSanPhamTrongGioHang = new JTable();
        pnPhaiDuoiLapHoaDon = new JPanel();
        pnCamera = new JPanel();
        pnHoaDonLuuTam = new JPanel();
        spHoaDonLuuTam = new JScrollPane();
        tbHoaDonLuuTam = new JTable();
        txtTimKiemHoaDonLuuTam = new JTextField();
        pnPhaiLapHoaDon = new JPanel();
        pnThongTinHoaDon = new JPanel();
        pnThongTInKhachHang = new JPanel();
        jLabel3 = new JLabel();
        jLabel5 = new JLabel();
        txtTenKhachHang = new JTextField();
        txtSoDienThoaiKh = new JTextField();
        jLabel8 = new JLabel();
        jCheckBox1 = new JCheckBox();
        pnThonhTinNhanVien = new JPanel();
        lbMaNhanVien = new JLabel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        txtTenNhanVien = new JTextField();
        txtMaNhanVien = new JTextField();
        txtSoDienTHoaiNv = new JTextField();
        pnTHongTinHoaDon = new JPanel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel9 = new JLabel();
        txtTienKhachDua = new JTextField();
        txtThue = new JTextField();
        txtTongTIen = new JTextField();
        jLabel4 = new JLabel();
        txtNgayLapHoaDon = new JTextField();
        jLabel10 = new JLabel();
        txtMaHoaDon = new JTextField();
        txtGiamGia = new JTextField();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        txtTienDu = new JTextField();
        btnLapHoaDon = new JButton();
        btnLuuTam = new JButton();

        panel2.setPreferredSize(new java.awt.Dimension(390, 100));

        listProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listProduct);

        GroupLayout panel2Layout = new GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        );

        menuProduct.setFocusable(false);

        pnTTKH.setPreferredSize(new java.awt.Dimension(390, 100));

        listKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listKhachHang);

        GroupLayout pnTTKHLayout = new GroupLayout(pnTTKH);
        pnTTKH.setLayout(pnTTKHLayout);
        pnTTKHLayout.setHorizontalGroup(
            pnTTKHLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 242, GroupLayout.PREFERRED_SIZE)
        );
        pnTTKHLayout.setVerticalGroup(
            pnTTKHLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
        );

        menuKhachHang.setFocusable(false);

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGLapHoaDon.setBackground(new Color(255, 255, 255));
        pnBGLapHoaDon.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnTraiLapHoaDon.setBackground(new Color(255, 255, 255));

        pnPhaiTrenLapHoaDon.setBackground(new Color(255, 255, 255));

        txtTimKiemSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimKiemSanPham.setText("");
        txtTimKiemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSanPhamActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setBorder(BorderFactory.createTitledBorder(null, "Danh sách các sản phẩm trong giỏ hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        spDanhSachCacSanPhamTrongGioHang.setBackground(new Color(255, 255, 255));

        tbDanhSachCacSanPhamTrongGioHang.setModel(new DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Số thứ tự", "Mã sản phẩm", "Tên sản phẩm", "Kích thước", "Số lượng", "Đơn giá", "Thành tiền", ""
            }
        ));
        tbDanhSachCacSanPhamTrongGioHang.setRowHeight(40);
        tbDanhSachCacSanPhamTrongGioHang.setSelectionBackground(new Color(0, 255, 58));
        tbDanhSachCacSanPhamTrongGioHang.setSelectionForeground(new Color(243, 7, 7));
        spDanhSachCacSanPhamTrongGioHang.setViewportView(tbDanhSachCacSanPhamTrongGioHang);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachCacSanPhamTrongGioHang)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachCacSanPhamTrongGioHang, GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        GroupLayout pnPhaiTrenLapHoaDonLayout = new GroupLayout(pnPhaiTrenLapHoaDon);
        pnPhaiTrenLapHoaDon.setLayout(pnPhaiTrenLapHoaDonLayout);
        pnPhaiTrenLapHoaDonLayout.setHorizontalGroup(
            pnPhaiTrenLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPhaiTrenLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                        .addComponent(txtTimKiemSanPham, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnPhaiTrenLapHoaDonLayout.setVerticalGroup(
            pnPhaiTrenLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemSanPham, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPhaiDuoiLapHoaDon.setBackground(new Color(255, 255, 255));

        pnCamera.setBackground(new Color(255, 255, 255));
        pnCamera.setBorder(BorderFactory.createTitledBorder(null, "Camera", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        GroupLayout pnCameraLayout = new GroupLayout(pnCamera);
        pnCamera.setLayout(pnCameraLayout);
        pnCameraLayout.setHorizontalGroup(
            pnCameraLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        pnCameraLayout.setVerticalGroup(
            pnCameraLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnHoaDonLuuTam.setBackground(new Color(255, 255, 255));
        pnHoaDonLuuTam.setBorder(BorderFactory.createTitledBorder(null, "Hoá đơn lưu tạm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tbHoaDonLuuTam.setModel(new DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Số thứ tự", "Tên khách hàng", "Số điện thoại", ""
            }
        ));
        tbHoaDonLuuTam.setRowHeight(40);
        tbHoaDonLuuTam.setSelectionBackground(new Color(0, 255, 91));
        tbHoaDonLuuTam.setSelectionForeground(new Color(255, 0, 0));
        spHoaDonLuuTam.setViewportView(tbHoaDonLuuTam);

        GroupLayout pnHoaDonLuuTamLayout = new GroupLayout(pnHoaDonLuuTam);
        pnHoaDonLuuTam.setLayout(pnHoaDonLuuTamLayout);
        pnHoaDonLuuTamLayout.setHorizontalGroup(
            pnHoaDonLuuTamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spHoaDonLuuTam, GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        pnHoaDonLuuTamLayout.setVerticalGroup(
            pnHoaDonLuuTamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spHoaDonLuuTam, GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        txtTimKiemHoaDonLuuTam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimKiemHoaDonLuuTam.setText("");
        txtTimKiemHoaDonLuuTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemHoaDonLuuTamActionPerformed(evt);
            }
        });

        GroupLayout pnPhaiDuoiLapHoaDonLayout = new GroupLayout(pnPhaiDuoiLapHoaDon);
        pnPhaiDuoiLapHoaDon.setLayout(pnPhaiDuoiLapHoaDonLayout);
        pnPhaiDuoiLapHoaDonLayout.setHorizontalGroup(
            pnPhaiDuoiLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiDuoiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnCamera, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPhaiDuoiLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiemHoaDonLuuTam)
                    .addComponent(pnHoaDonLuuTam, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnPhaiDuoiLapHoaDonLayout.setVerticalGroup(
            pnPhaiDuoiLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiDuoiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnHoaDonLuuTam, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemHoaDonLuuTam, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(pnCamera, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout pnTraiLapHoaDonLayout = new GroupLayout(pnTraiLapHoaDon);
        pnTraiLapHoaDon.setLayout(pnTraiLapHoaDonLayout);
        pnTraiLapHoaDonLayout.setHorizontalGroup(
            pnTraiLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnPhaiTrenLapHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPhaiDuoiLapHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTraiLapHoaDonLayout.setVerticalGroup(
            pnTraiLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTraiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnPhaiTrenLapHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPhaiDuoiLapHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPhaiLapHoaDon.setBackground(new Color(255, 255, 255));

        pnThongTinHoaDon.setBackground(new Color(255, 255, 255));
        pnThongTinHoaDon.setBorder(BorderFactory.createTitledBorder(null, "Thông tin hoá đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        pnThongTInKhachHang.setBackground(new Color(255, 255, 255));
        pnThongTInKhachHang.setBorder(BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new Color(0, 51, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tên khách hàng:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Số điện thoại:");

        txtTenKhachHang.setEnabled(false);

        txtSoDienThoaiKh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiKhActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Khách vãng lai:");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox1.setText("Tin chuẩn chưa");

        GroupLayout pnThongTInKhachHangLayout = new GroupLayout(pnThongTInKhachHang);
        pnThongTInKhachHang.setLayout(pnThongTInKhachHangLayout);
        pnThongTInKhachHangLayout.setHorizontalGroup(
            pnThongTInKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(21, 21, 21)
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoDienThoaiKh)
                    .addComponent(txtTenKhachHang, GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addGroup(pnThongTInKhachHangLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnThongTInKhachHangLayout.setVerticalGroup(
            pnThongTInKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtTenKhachHang))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDienThoaiKh, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnThonhTinNhanVien.setBackground(new Color(255, 255, 255));
        pnThonhTinNhanVien.setBorder(BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new Color(0, 51, 255))); // NOI18N

        lbMaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaNhanVien.setText("Mã nhân viên:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tên nhân viên:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Số điện thoại:");

        txtTenNhanVien.setEnabled(false);

        txtMaNhanVien.setEnabled(false);

        txtSoDienTHoaiNv.setEnabled(false);

        GroupLayout pnThonhTinNhanVienLayout = new GroupLayout(pnThonhTinNhanVien);
        pnThonhTinNhanVien.setLayout(pnThonhTinNhanVienLayout);
        pnThonhTinNhanVienLayout.setHorizontalGroup(
            pnThonhTinNhanVienLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                        .addComponent(lbMaNhanVien)
                        .addGap(11, 11, 11)
                        .addComponent(txtMaNhanVien, GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                    .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                        .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                                .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)))
                        .addGap(6, 6, 6)
                        .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNhanVien)
                            .addComponent(txtSoDienTHoaiNv, GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnThonhTinNhanVienLayout.setVerticalGroup(
            pnThonhTinNhanVienLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMaNhanVien, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtMaNhanVien))
                .addGap(18, 18, 18)
                .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenNhanVien)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtSoDienTHoaiNv)))
        );

        pnTHongTinHoaDon.setBackground(new Color(255, 255, 255));
        pnTHongTinHoaDon.setBorder(BorderFactory.createTitledBorder(null, "Thông tin hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new Color(0, 51, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tiền khách đưa:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Thuế:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tổng tiền:");

        txtTienKhachDua.setEnabled(false);

        txtThue.setEnabled(false);

        txtTongTIen.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ngày lập hoá đơn:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Mã hoá đơn:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Giảm giá:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tiền dư:");

        GroupLayout pnTHongTinHoaDonLayout = new GroupLayout(pnTHongTinHoaDon);
        pnTHongTinHoaDon.setLayout(pnTHongTinHoaDonLayout);
        pnTHongTinHoaDonLayout.setHorizontalGroup(
            pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(txtTienKhachDua))
                    .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiamGia, GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtThue)))
                            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayLapHoaDon)
                                    .addComponent(txtMaHoaDon)))
                            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(75, 75, 75)
                                .addComponent(txtTongTIen, GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTienDu, GroupLayout.PREFERRED_SIZE, 248, GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnTHongTinHoaDonLayout.setVerticalGroup(
            pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtMaHoaDon))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayLapHoaDon, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThue, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiamGia)
                    .addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTIen, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienKhachDua, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTienDu)
                    .addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLapHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLapHoaDon.setText("Lập hoá đơn");
        btnLapHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHoaDonActionPerformed(evt);
            }
        });

        btnLuuTam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLuuTam.setText("Lưu tạm hóa đơn");
        btnLuuTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuTamActionPerformed(evt);
            }
        });

        GroupLayout pnThongTinHoaDonLayout = new GroupLayout(pnThongTinHoaDon);
        pnThongTinHoaDon.setLayout(pnThongTinHoaDonLayout);
        pnThongTinHoaDonLayout.setHorizontalGroup(
            pnThongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTInKhachHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTHongTinHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnThongTinHoaDonLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnLapHoaDon)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuuTam)
                .addGap(37, 37, 37))
            .addGroup(pnThongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(pnThonhTinNhanVien, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinHoaDonLayout.setVerticalGroup(
            pnThongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(pnThongTInKhachHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTHongTinHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLapHoaDon, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuTam, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
            .addGroup(pnThongTinHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(pnThongTinHoaDonLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(pnThonhTinNhanVien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(719, Short.MAX_VALUE)))
        );

        GroupLayout pnPhaiLapHoaDonLayout = new GroupLayout(pnPhaiLapHoaDon);
        pnPhaiLapHoaDon.setLayout(pnPhaiLapHoaDonLayout);
        pnPhaiLapHoaDonLayout.setHorizontalGroup(
            pnPhaiLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnThongTinHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        pnPhaiLapHoaDonLayout.setVerticalGroup(
            pnPhaiLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnThongTinHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        GroupLayout pnBGLapHoaDonLayout = new GroupLayout(pnBGLapHoaDon);
        pnBGLapHoaDon.setLayout(pnBGLapHoaDonLayout);
        pnBGLapHoaDonLayout.setHorizontalGroup(
            pnBGLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnBGLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnTraiLapHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPhaiLapHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        pnBGLapHoaDonLayout.setVerticalGroup(
            pnBGLapHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnTraiLapHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPhaiLapHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGLapHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGLapHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemHoaDonLuuTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemHoaDonLuuTamActionPerformed
        if (txtTimKiemHoaDonLuuTam.getText().equalsIgnoreCase("Tìm kiếm hoá đơn lưu tạm")) {
        txtTimKiemHoaDonLuuTam.setText("");
        txtTimKiemHoaDonLuuTam.setForeground(Color.BLACK); // Đổi màu văn bản khi bắt đầu nhập
    }
    }//GEN-LAST:event_txtTimKiemHoaDonLuuTamActionPerformed

    private void txtTimKiemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSanPhamActionPerformed
        if(txtTimKiemSanPham.getText().equalsIgnoreCase("Tìm kiếm sản phẩm")){
            txtTimKiemSanPham.setText("");
            txtTimKiemSanPham.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTimKiemSanPhamActionPerformed

    private void btnLapHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHoaDonActionPerformed
    }//GEN-LAST:event_btnLapHoaDonActionPerformed

    private void btnLuuTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuTamActionPerformed
        // TODO add your handling code here:
//        System.out.println("Đã lưu bản nháp hoá đơm");
    }//GEN-LAST:event_btnLuuTamActionPerformed

    private void txtSoDienThoaiKhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiKhActionPerformed

   public JTextField getTxtTimKiemSanPham(){
        return txtTimKiemSanPham;
    }
    public JTable getTbDanhSachCacSanPhamTrongGioHang(){
        return tbDanhSachCacSanPhamTrongGioHang;
    }
    public JTextField getTxtTimKiemHoaDonLuuTam(){
        return txtTimKiemHoaDonLuuTam;
    }
    public JPopupMenu getMenuKhachHang(){
        return menuKhachHang;
    }
    public JList getListKhachHang(){
        return listKhachHang;
    }
    public JTextField getTxtSoDienThoaiKh(){
        return txtSoDienThoaiKh;
    }
    public JPopupMenu getMenuProduct(){
        return menuProduct;
    }
    public JList getListProduct(){
        return listProduct;
    }
    public JPanel getPnCamera(){
        return pnCamera;
    }
    public JTextField getTxtTenNhanVien(){
        return txtTenNhanVien;
    }
    public JTextField getTxtMaNhanVien(){
        return txtMaNhanVien;
    }
    public JTextField getTxtSoDienTHoaiNv(){
        return txtSoDienTHoaiNv;
    }
    public JTextField getTxtTenKhachHang(){
        return txtTenKhachHang;
    }
    public JButton getBtnLapHoaDon(){
        return btnLapHoaDon;
    }
    public JButton getBtnLuuTam(){
        return btnLuuTam;
    }
    public JTextField getTxtMaHoaDon(){
        return txtMaHoaDon;
    }
    public JTextField getTxtNgayLapHoaDon(){
        return txtNgayLapHoaDon;
    }
    public JTextField getTxtThue(){
        return txtThue;
    }
    public JTextField getTxtGiamGia(){
        return txtGiamGia;
    }
    public JTextField getTxtTongTIen(){
        return txtTongTIen;
    }
    public JTextField getTxtTienKhachDua(){
        return txtTienKhachDua;
    }
    public JTextField getTxtTienDu(){
        return txtTienDu;
    }
    public JTable getTbHoaDonLuuTam(){
        return tbHoaDonLuuTam;
    }
    public JCheckBox getjCheckBox1(){
        return jCheckBox1;
    }
    public JTextField getTxtChietKhau(){
        return txtGiamGia;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnLapHoaDon;
    private JButton btnLuuTam;
    private JCheckBox jCheckBox1;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JLabel lbMaNhanVien;
    private JList<String> listKhachHang;
    private JList<String> listProduct;
    private JPopupMenu menuKhachHang;
    private JPopupMenu menuProduct;
    private java.awt.Panel panel2;
    private JPanel pnBGLapHoaDon;
    private JPanel pnCamera;
    private JPanel pnHoaDonLuuTam;
    private JPanel pnPhaiDuoiLapHoaDon;
    private JPanel pnPhaiLapHoaDon;
    private JPanel pnPhaiTrenLapHoaDon;
    private JPanel pnTHongTinHoaDon;
    private java.awt.Panel pnTTKH;
    private JPanel pnThongTInKhachHang;
    private JPanel pnThongTinHoaDon;
    private JPanel pnThonhTinNhanVien;
    private JPanel pnTraiLapHoaDon;
    private JScrollPane spDanhSachCacSanPhamTrongGioHang;
    private JScrollPane spHoaDonLuuTam;
    private JTable tbDanhSachCacSanPhamTrongGioHang;
    private JTable tbHoaDonLuuTam;
    private JTextField txtGiamGia;
    private JTextField txtMaHoaDon;
    private JTextField txtMaNhanVien;
    private JTextField txtNgayLapHoaDon;
    private JTextField txtSoDienTHoaiNv;
    private JTextField txtSoDienThoaiKh;
    private JTextField txtTenKhachHang;
    private JTextField txtTenNhanVien;
    private JTextField txtThue;
    private JTextField txtTienDu;
    private JTextField txtTienKhachDua;
    private JTextField txtTimKiemHoaDonLuuTam;
    private JTextField txtTimKiemSanPham;
    private JTextField txtTongTIen;
    // End of variables declaration//GEN-END:variables
}
