/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;
import dev.skyherobrine.app.controllers.dashboardui.QuanLyHoaDon.PhieuTraKHController;
//import dev.skyherobrine.app.controllers.dashboardui.QuanLyHoaDon.PhieuTraKHController;

import javax.swing.*;

/**
 *
 * @author Virtue Nguyen
 */
public class QuanLyPhieuTraHangChoKhachHang extends JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public QuanLyPhieuTraHangChoKhachHang() {
        initComponents();
        PhieuTraKHController controller = new PhieuTraKHController(this);
        menuSuggestHD.add(pnSuggestHD);
        txtTimKiemHoaDon.addKeyListener(controller);
        listSuggestHD.addKeyListener(controller);
        tbDanhSachSanPhamTrongHoaDon.getModel().addTableModelListener(controller);
        txtMaHoaDon.setEnabled(false);
        txtNgayLapPhieu.setEnabled(false);
        txtGiamGia.setEnabled(false);
        txtTongTienHang.setEnabled(false);
        txtTongTienTraLai.setEnabled(false);
        jDateChooserNgayLapPhieu.setEnabled(false);
        jDateChooserTkTuNgay.addPropertyChangeListener("date", controller);
        jDateChooserTkDenNgay.addPropertyChangeListener("date", controller);
        btnTraHang.addActionListener(controller);
        txtTuKhoaTimKiem.addKeyListener(controller);
        jDateChooserTkDenNgay.setEnabled(false);
        tbDanhSachPhieuTraHangChoKhachHang.addMouseListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSuggestHD = new java.awt.Panel();
        jScrollPane2 = new JScrollPane();
        listSuggestHD = new JList<>();
        menuSuggestHD = new JPopupMenu();
        pnBGThongTinCaNhan = new JPanel();
        pnThongTInPhieuTraHang = new JPanel();
        lbMaPhieuTra = new JLabel();
        txtMaPhieuTra = new JTextField();
        lbMaPhieuNhap = new JLabel();
        lbNgayLapPhieu = new JLabel();
        lbXuatXuQuanLySanPham = new JLabel();
        txtLyDoTraHang = new JTextField();
        txtMaPhieuNhap = new JTextField();
        jDateChooserNgayLapPhieu = new JDateChooser();
        pnDanhSachPhieuTraHang = new JPanel();
        spDanhSachPhieuTraHangChoKhachHang = new JScrollPane();
        tbDanhSachPhieuTraHangChoKhachHang = new JTable();
        pnTimKiemPhieuTraHang = new JPanel();
        jLabel1 = new JLabel();
        jDateChooserTkTuNgay = new JDateChooser();
        jLabel2 = new JLabel();
        jDateChooserTkDenNgay = new JDateChooser();
        txtTuKhoaTimKiem = new JTextField();
        jLabel3 = new JLabel();
        pnDanhSachCacSanPhamTrongHoaDon = new JPanel();
        jScrollPane1 = new JScrollPane();
        tbDanhSachSanPhamTrongHoaDon = new JTable();
        txtTimKiemHoaDon = new JTextField();
        jPanel1 = new JPanel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        txtNgayLapPhieu = new JTextField();
        txtMaHoaDon = new JTextField();
        txtGiamGia = new JTextField();
        txtTongTienHang = new JTextField();
        txtTongTienTraLai = new JTextField();
        txtGhiChu = new JTextField();
        btnTraHang = new JButton();

        pnSuggestHD.setPreferredSize(new java.awt.Dimension(347, 96));

        listSuggestHD.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listSuggestHD);

        GroupLayout pnSuggestHDLayout = new GroupLayout(pnSuggestHD);
        pnSuggestHD.setLayout(pnSuggestHDLayout);
        pnSuggestHDLayout.setHorizontalGroup(
            pnSuggestHDLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        pnSuggestHDLayout.setVerticalGroup(
            pnSuggestHDLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        menuSuggestHD.setFocusable(false);

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnThongTInPhieuTraHang.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTInPhieuTraHang.setBorder(BorderFactory.createTitledBorder(null, "Thông tin phiếu trả hàng của khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        pnThongTInPhieuTraHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lbMaPhieuTra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaPhieuTra.setHorizontalAlignment(SwingConstants.RIGHT);
        lbMaPhieuTra.setText("Mã hoá đơn:");

        txtMaPhieuTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaPhieuTra.setEnabled(false);
        txtMaPhieuTra.setPreferredSize(new java.awt.Dimension(64, 25));

        lbMaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaPhieuNhap.setText("Mã phiếu nhập:");

        lbNgayLapPhieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgayLapPhieu.setText("Ngày lập phiếu:");

        lbXuatXuQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbXuatXuQuanLySanPham.setText("Lý do trả hàng:");

        txtLyDoTraHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLyDoTraHang.setEnabled(false);

        txtMaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaPhieuNhap.setEnabled(false);

        GroupLayout pnThongTInPhieuTraHangLayout = new GroupLayout(pnThongTInPhieuTraHang);
        pnThongTInPhieuTraHang.setLayout(pnThongTInPhieuTraHangLayout);
        pnThongTInPhieuTraHangLayout.setHorizontalGroup(
            pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInPhieuTraHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, pnThongTInPhieuTraHangLayout.createSequentialGroup()
                        .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaPhieuTra)
                            .addComponent(lbMaPhieuNhap))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnThongTInPhieuTraHangLayout.createSequentialGroup()
                        .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lbNgayLapPhieu)
                            .addComponent(lbXuatXuQuanLySanPham))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaPhieuTra, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLyDoTraHang)
                            .addComponent(txtMaPhieuNhap)
                            .addComponent(jDateChooserNgayLapPhieu, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnThongTInPhieuTraHangLayout.setVerticalGroup(
            pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInPhieuTraHangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuTra, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaPhieuTra, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuNhap, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaPhieuNhap, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserNgayLapPhieu, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNgayLapPhieu))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLyDoTraHang, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbXuatXuQuanLySanPham, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDanhSachPhieuTraHang.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachPhieuTraHang.setBorder(BorderFactory.createTitledBorder(null, "Danh Sách phiếu trả hàng của khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        tbDanhSachPhieuTraHangChoKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spDanhSachPhieuTraHangChoKhachHang.setViewportView(tbDanhSachPhieuTraHangChoKhachHang);

        GroupLayout pnDanhSachPhieuTraHangLayout = new GroupLayout(pnDanhSachPhieuTraHang);
        pnDanhSachPhieuTraHang.setLayout(pnDanhSachPhieuTraHangLayout);
        pnDanhSachPhieuTraHangLayout.setHorizontalGroup(
            pnDanhSachPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachPhieuTraHangChoKhachHang, GroupLayout.Alignment.TRAILING)
        );
        pnDanhSachPhieuTraHangLayout.setVerticalGroup(
            pnDanhSachPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachPhieuTraHangChoKhachHang, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pnTimKiemPhieuTraHang.setBackground(new java.awt.Color(255, 255, 255));
        pnTimKiemPhieuTraHang.setBorder(BorderFactory.createTitledBorder(null, "Tìm Kiếm phiếu trả hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Từ ngày:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Đến ngày:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Từ khoá tìm kiếm:");

        GroupLayout pnTimKiemPhieuTraHangLayout = new GroupLayout(pnTimKiemPhieuTraHang);
        pnTimKiemPhieuTraHang.setLayout(pnTimKiemPhieuTraHangLayout);
        pnTimKiemPhieuTraHangLayout.setHorizontalGroup(
            pnTimKiemPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemPhieuTraHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTkTuNgay, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTkDenNgay, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoaTimKiem, GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTimKiemPhieuTraHangLayout.setVerticalGroup(
            pnTimKiemPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemPhieuTraHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserTkTuNgay, GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jDateChooserTkDenNgay, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTimKiemPhieuTraHangLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(txtTuKhoaTimKiem, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnDanhSachCacSanPhamTrongHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachCacSanPhamTrongHoaDon.setBorder(BorderFactory.createTitledBorder(null, "Danh sách sản phẩm trong hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tbDanhSachSanPhamTrongHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tbDanhSachSanPhamTrongHoaDon);

        GroupLayout pnDanhSachCacSanPhamTrongHoaDonLayout = new GroupLayout(pnDanhSachCacSanPhamTrongHoaDon);
        pnDanhSachCacSanPhamTrongHoaDon.setLayout(pnDanhSachCacSanPhamTrongHoaDonLayout);
        pnDanhSachCacSanPhamTrongHoaDonLayout.setHorizontalGroup(
            pnDanhSachCacSanPhamTrongHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnDanhSachCacSanPhamTrongHoaDonLayout.setVerticalGroup(
            pnDanhSachCacSanPhamTrongHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhSachCacSanPhamTrongHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(BorderFactory.createTitledBorder(null, "Phiếu trả hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mã hoá đơn:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Ngày lập phiếu:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Giảm giá:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Tổng tiền hàng:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tổng tiền trả lại:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Ghi chú:");

        btnTraHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTraHang.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/icon-tra-hang.png"))); // NOI18N
        btnTraHang.setText("Trả hàng");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayLapPhieu, GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGiamGia, GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTongTienHang)
                            .addComponent(txtMaHoaDon)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(txtGhiChu)
                            .addComponent(txtTongTienTraLai))))
                .addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(btnTraHang, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtMaHoaDon))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNgayLapPhieu)
                    .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiamGia)
                    .addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienHang)
                    .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienTraLai)
                    .addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtGhiChu))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTraHang, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout pnBGThongTinCaNhanLayout = new GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnDanhSachPhieuTraHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTimKiemPhieuTraHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDanhSachCacSanPhamTrongHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTimKiemHoaDon, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnThongTInPhieuTraHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addComponent(pnDanhSachPhieuTraHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnTimKiemPhieuTraHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnThongTInPhieuTraHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiemHoaDon, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnDanhSachCacSanPhamTrongHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtMaPhieuTra() {
        return txtMaPhieuTra;
    }
    public JDateChooser getjDateChooserTkNgayHenLay() {
        return jDateChooserTkDenNgay;
    }
    public JDateChooser getjDateChooserTkNgayLap() {
        return jDateChooserTkTuNgay;
    }
    public JTextField getTxtLyDoTraHang() {
        return txtLyDoTraHang;
    }
    public JTextField getTxtMaPhieuNhap() {
        return txtMaPhieuNhap;
    }
//    public JTextField getTxtSoLuongTra() {
//        return txtSoLuongTra;
//    }
    public JTextField getTxtTuKhoaTimKiem() {
        return txtTuKhoaTimKiem;
    }
//    public JTextField getTxtTinhTrang() {
//        return txtTinhTrang;
//    }
//    public JTextField getTxtTenNhaCungCapSanPham() {
//        return txtTenNhaCungCapSanPham;
//    }
//    public JTextField getTxtTenSanPham() {
//        return txtTenSanPham;
//    }
    public JDateChooser getjDateChooserNgayLapPhieu() {
        return jDateChooserNgayLapPhieu;
    }
    public JTable getTbDanhSachPhieuTraHangChoKhachHang() {
        return tbDanhSachPhieuTraHangChoKhachHang;
    }
    public JTable getTbDanhSachSanPhamTrongHoaDon() {
        return tbDanhSachSanPhamTrongHoaDon;
    }
    public JTextField getTxtGhiChu() {
        return txtGhiChu;
    }
    public JTextField getTxtGiamGia() {
        return txtGiamGia;
    }
    public JTextField getTxtMaHoaDon() {
        return txtMaHoaDon;
    }
    public JTextField getTxtNgayLapPhieu() {
        return txtNgayLapPhieu;
    }
    public JTextField getTxtTongTienHang() {
        return txtTongTienHang;
    }
    public JTextField getTxtTongTienTraLai() {
        return txtTongTienTraLai;
    }
    public JButton getBtnTraHang() {
        return btnTraHang;
    }
    public JTextField getTxtTimKiemHoaDon() {
        return txtTimKiemHoaDon;
    }
    public JList<String> getListSuggestHD() {
        return listSuggestHD;
    }
    public JPopupMenu getMenuSuggestHD() {
        return menuSuggestHD;
    }
    public JDateChooser getjDateChooserNgayLap(){
        return jDateChooserNgayLapPhieu;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnTraHang;
    private JDateChooser jDateChooserNgayLapPhieu;
    private JDateChooser jDateChooserTkDenNgay;
    private JDateChooser jDateChooserTkTuNgay;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JLabel lbMaPhieuNhap;
    private JLabel lbMaPhieuTra;
    private JLabel lbNgayLapPhieu;
    private JLabel lbXuatXuQuanLySanPham;
    private JList<String> listSuggestHD;
    private JPopupMenu menuSuggestHD;
    private JPanel pnBGThongTinCaNhan;
    private JPanel pnDanhSachCacSanPhamTrongHoaDon;
    private JPanel pnDanhSachPhieuTraHang;
    private java.awt.Panel pnSuggestHD;
    private JPanel pnThongTInPhieuTraHang;
    private JPanel pnTimKiemPhieuTraHang;
    private JScrollPane spDanhSachPhieuTraHangChoKhachHang;
    private JTable tbDanhSachPhieuTraHangChoKhachHang;
    private JTable tbDanhSachSanPhamTrongHoaDon;
    private JTextField txtGhiChu;
    private JTextField txtGiamGia;
    private JTextField txtLyDoTraHang;
    private JTextField txtMaHoaDon;
    private JTextField txtMaPhieuNhap;
    private JTextField txtMaPhieuTra;
    private JTextField txtNgayLapPhieu;
    private JTextField txtTimKiemHoaDon;
    private JTextField txtTongTienHang;
    private JTextField txtTongTienTraLai;
    private JTextField txtTuKhoaTimKiem;
    // End of variables declaration//GEN-END:variables
}
