/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;
//import dev.skyherobrine.app.controllers.dashboardui.product.ProductController;
import dev.skyherobrine.app.controllers.dashboardui.product.ProductController;
import dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionEvent;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;


/**
 *
 * @author Virtue Nguyen
 */
public class QuanLySanPham extends JPanel {
    /**
     * Creates new form ThongTinCaNhan
     */
    public QuanLySanPham()  {
        initComponents();
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onDelete(int row) {
                if(tbDIalogDanhSachCacSanPham.isEditing()){
                    tbDIalogDanhSachCacSanPham.getCellEditor().stopCellEditing();
                }
                DefaultTableModel defaultTableModel =  (DefaultTableModel) tbDIalogDanhSachCacSanPham.getModel();
                defaultTableModel.removeRow(row);
            }
        };
        ProductController controller = new ProductController(this);
        tbDIalogDanhSachCacSanPham.getColumnModel().getColumn(3).setCellRenderer(new dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellRender());
        tbDIalogDanhSachCacSanPham.getColumnModel().getColumn(3).setCellEditor(new dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellEditor(controller));
        tbDanhSachSanPham.addMouseListener(controller);
        btnThemQuanLySanPham.addActionListener(controller);
        btnSuaQuanLySanPham.addActionListener(controller);
        btnXoaQuanLySanPham.addActionListener(controller);
        cbTkDanhMuc.addActionListener(controller);
        cbTkLoaiSanPham.addActionListener(controller);
        cbTkTinhTrang.addActionListener(controller);
        cbTkTHuongHieu.addActionListener(controller);
        cbTkDoTuoi.addActionListener(controller);
        cbTkKieuNguoiMacSp.addActionListener(controller);
//
        txtTuKhoaTimKiem.addKeyListener(controller);
//        btnThemAnhSanPham.addActionListener(new ProductController(this));
        btnThemPBSP.addActionListener(controller);
        tbDanhSachSanPham.addMouseListener(controller);
        jDateChooserNgaySanXuat.setEnabled(false);
        cbDoTuoi.setEnabled(false);
        cbDanhMuc.setEnabled(false);
        cbKieuNguoiMac.setEnabled(false);
        cbLoaiSanPham.setEnabled(false);
        cbTh.setEnabled(false);
        cbTinhTrang.setEnabled(false);
        tbDIalogDanhSachCacSanPham.addMouseListener(controller);
        btnDialogThemXuong.addActionListener(controller);
        btnDialogAnh.addActionListener(controller);
        btnThemQuanLySanPham.addActionListener(controller);
        btnXoaQuanLySanPham.addActionListener(controller);
        btnSuaQuanLySanPham.addActionListener(controller);
        cbLoaiSanPham.addActionListener(controller);
        cbKieuNguoiMac.addActionListener(controller);
        tbDIalogDanhSachCacSanPham.getModel().addTableModelListener(controller);
        txtDialogMaSanPham.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winThemPBSP = new JDialog();
        jPanel1 = new JPanel();
        jLabel5 = new JLabel();
        txtDialogMaSanPham = new JTextField();
        jPanel2 = new JPanel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        cbDialogKichThuoc = new JComboBox<>();
        cbDialogMauSac = new JComboBox<>();
        txtDialogSoLuong = new JTextField();
        pnDialogAnh = new JPanel();
        btnDialogAnh = new JButton();
        jPanel4 = new JPanel();
        spDialogDanhSachPhienBanSanPham = new JScrollPane();
        tbDIalogDanhSachCacSanPham = new JTable();
        btnDialogXong = new JButton();
        btnDialogThemXuong = new JButton();
        pnBGThongTinCaNhan = new JPanel();
        pnThongTinSanPhamQuanLySanPham = new JPanel();
        lbMaSpQuanLySanPham = new JLabel();
        txtMaSpQuanLySanPham = new JTextField();
        lbMaLoaiSpQuanLySanPham = new JLabel();
        lbHhQuanLySanPham = new JLabel();
        lbTenSpQuanLySanPham = new JLabel();
        txtTenSpQuanLySanPham = new JTextField();
        lbNgaySanXuatQuanLySanPham = new JLabel();
        lbXuatXuQuanLySanPham = new JLabel();
        txtXuatXuQuanLySanPham = new JTextField();
        lbDoTuoiQuanLySanPham = new JLabel();
        txtPhanTramLoiQuanLySanPham = new JTextField();
        lbPhanTramLoiQuanLySanPham = new JLabel();
        lbPhongCachMguoiMacQuanLySanPham1 = new JLabel();
        btnSuaQuanLySanPham = new JButton();
        btnThemQuanLySanPham = new JButton();
        btnXoaQuanLySanPham = new JButton();
        cbLoaiSanPham = new JComboBox<>();
        cbTh = new JComboBox<>();
        cbKieuNguoiMac = new JComboBox<>();
        cbDoTuoi = new JComboBox<>();
        cbTinhTrang = new JComboBox<>();
        cbDanhMuc = new JComboBox<>();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jDateChooserNgaySanXuat = new JDateChooser();
        jLabel4 = new JLabel();
        btnThemPBSP = new JButton();
        PnDanhSachSanPhamQuanLySanPham = new JPanel();
        spDanhSachSapnPham = new JScrollPane();
        tbDanhSachSanPham = new JTable();
        pnTimKiemQuanLySanPham = new JPanel();
        cbTkKieuNguoiMacSp = new JComboBox<>();
        cbTkDanhMuc = new JComboBox<>();
        cbTkLoaiSanPham = new JComboBox<>();
        cbTkTinhTrang = new JComboBox<>();
        cbTkTHuongHieu = new JComboBox<>();
        cbTkDoTuoi = new JComboBox<>();
        jLabel1 = new JLabel();
        txtTuKhoaTimKiem = new JTextField();

        winThemPBSP.setModal(true);
        winThemPBSP.setResizable(false);
        winThemPBSP.setSize(new Dimension(660, 800));

        jPanel1.setBackground(new Color(255, 255, 255));

        jLabel5.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mã sản phẩm:");

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setBorder(BorderFactory.createTitledBorder(null, "Phiên bản sản phẩm", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 18))); // NOI18N

        jLabel6.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Màu sắc:");

        jLabel7.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Kích thước:");

        jLabel8.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Số lượng:");

        cbDialogKichThuoc.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        cbDialogKichThuoc.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDialogKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDialogKichThuocActionPerformed(evt);
            }
        });

        cbDialogMauSac.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        cbDialogMauSac.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDialogSoLuong.setFont(new Font("Segoe UI", 0, 14)); // NOI18N

        GroupLayout pnDialogAnhLayout = new GroupLayout(pnDialogAnh);
        pnDialogAnh.setLayout(pnDialogAnhLayout);
        pnDialogAnhLayout.setHorizontalGroup(
            pnDialogAnhLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );
        pnDialogAnhLayout.setVerticalGroup(
            pnDialogAnhLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        btnDialogAnh.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        btnDialogAnh.setText("Ảnh");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pnDialogAnh, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnDialogAnh, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(cbDialogMauSac, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE))
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDialogKichThuoc, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDialogSoLuong, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDialogMauSac, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDialogKichThuoc, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDialogSoLuong, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDialogAnh, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDialogAnh, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new Color(255, 255, 255));
        jPanel4.setBorder(BorderFactory.createTitledBorder(null, "Danh sách phiên bản sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 18))); // NOI18N

        tbDIalogDanhSachCacSanPham.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Màu sắc", "Kích thước", "Số lượng", ""
            }
        ));
        tbDIalogDanhSachCacSanPham.setRowHeight(40);
        spDialogDanhSachPhienBanSanPham.setViewportView(tbDIalogDanhSachCacSanPham);

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDialogDanhSachPhienBanSanPham)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDialogDanhSachPhienBanSanPham, GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        btnDialogXong.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnDialogXong.setText("Xong");

        btnDialogThemXuong.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnDialogThemXuong.setText("Thêm xuống");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDialogThemXuong)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDialogMaSanPham, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(btnDialogXong)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDialogMaSanPham, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDialogThemXuong, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDialogXong, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout winThemPBSPLayout = new GroupLayout(winThemPBSP.getContentPane());
        winThemPBSP.getContentPane().setLayout(winThemPBSPLayout);
        winThemPBSPLayout.setHorizontalGroup(
            winThemPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(winThemPBSPLayout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        winThemPBSPLayout.setVerticalGroup(
            winThemPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new Dimension(1651, 1000));

        pnThongTinSanPhamQuanLySanPham.setBackground(new Color(255, 255, 255));
        pnThongTinSanPhamQuanLySanPham.setBorder(BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 24))); // NOI18N
        pnThongTinSanPhamQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N

        lbMaSpQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbMaSpQuanLySanPham.setHorizontalAlignment(SwingConstants.RIGHT);
        lbMaSpQuanLySanPham.setText("Mã sản phẩm:");

        txtMaSpQuanLySanPham.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        txtMaSpQuanLySanPham.setEnabled(false);
        txtMaSpQuanLySanPham.setPreferredSize(new Dimension(64, 25));

        lbMaLoaiSpQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbMaLoaiSpQuanLySanPham.setHorizontalAlignment(SwingConstants.RIGHT);
        lbMaLoaiSpQuanLySanPham.setText("Loại sản phẩm:");

        lbHhQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbHhQuanLySanPham.setText("Thương hiệu:");

        lbTenSpQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbTenSpQuanLySanPham.setText("Tên sản phẩm:");

        txtTenSpQuanLySanPham.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        txtTenSpQuanLySanPham.setEnabled(false);
        txtTenSpQuanLySanPham.setPreferredSize(new Dimension(79, 33));

        lbNgaySanXuatQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbNgaySanXuatQuanLySanPham.setText("Ngày sản xuất:");

        lbXuatXuQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbXuatXuQuanLySanPham.setText("Xuất xứ:");

        txtXuatXuQuanLySanPham.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        txtXuatXuQuanLySanPham.setEnabled(false);

        lbDoTuoiQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbDoTuoiQuanLySanPham.setText("Độ tuổi:");

        txtPhanTramLoiQuanLySanPham.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        txtPhanTramLoiQuanLySanPham.setEnabled(false);

        lbPhanTramLoiQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbPhanTramLoiQuanLySanPham.setText("Phần trăm lời:");

        lbPhongCachMguoiMacQuanLySanPham1.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbPhongCachMguoiMacQuanLySanPham1.setText("Phong cách mặc:");

        btnSuaQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnSuaQuanLySanPham.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/edit.png"))); // NOI18N
        btnSuaQuanLySanPham.setText("Sửa sản phẩm");

        btnThemQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnThemQuanLySanPham.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/plus.png"))); // NOI18N
        btnThemQuanLySanPham.setText("Thêm sản phẩm");

        btnXoaQuanLySanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaQuanLySanPham.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/remove.png"))); // NOI18N
        btnXoaQuanLySanPham.setText("Xoá sản phẩm");

        cbLoaiSanPham.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        cbLoaiSanPham.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTh.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        cbTh.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbKieuNguoiMac.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        cbKieuNguoiMac.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDoTuoi.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        cbDoTuoi.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTinhTrang.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        cbTinhTrang.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDanhMuc.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        cbDanhMuc.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tình trạng:");

        jLabel3.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Danh mục:");

        jLabel4.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Phiên bản sản phẩm:");

        btnThemPBSP.setText("Thêm PBSP");

        GroupLayout pnThongTinSanPhamQuanLySanPhamLayout = new GroupLayout(pnThongTinSanPhamQuanLySanPham);
        pnThongTinSanPhamQuanLySanPham.setLayout(pnThongTinSanPhamQuanLySanPhamLayout);
        pnThongTinSanPhamQuanLySanPhamLayout.setHorizontalGroup(
            pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                                .addComponent(lbMaSpQuanLySanPham, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaSpQuanLySanPham, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNgaySanXuatQuanLySanPham)
                                    .addComponent(lbTenSpQuanLySanPham, GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDoTuoiQuanLySanPham, GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMaLoaiSpQuanLySanPham, GroupLayout.Alignment.LEADING))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenSpQuanLySanPham, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDoTuoi, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTinhTrang, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooserNgaySanXuat, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbLoaiSanPham, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(btnThemQuanLySanPham)))
                .addGap(234, 234, 234)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lbPhanTramLoiQuanLySanPham)
                            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(lbPhongCachMguoiMacQuanLySanPham1, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(lbXuatXuQuanLySanPham)
                            .addComponent(lbHhQuanLySanPham))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(txtXuatXuQuanLySanPham, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbTh, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbDanhMuc, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhanTramLoiQuanLySanPham, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbKieuNguoiMac, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnThemPBSP))
                        .addGap(116, 116, 116))
                    .addGroup(GroupLayout.Alignment.TRAILING, pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addComponent(btnSuaQuanLySanPham)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaQuanLySanPham)
                        .addGap(279, 279, 279))))
        );
        pnThongTinSanPhamQuanLySanPhamLayout.setVerticalGroup(
            pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaSpQuanLySanPham, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSpQuanLySanPham, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHhQuanLySanPham, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTh, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSpQuanLySanPham, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenSpQuanLySanPham, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbXuatXuQuanLySanPham, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXuatXuQuanLySanPham, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNgaySanXuatQuanLySanPham, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserNgaySanXuat, GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDoTuoiQuanLySanPham, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDoTuoi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDanhMuc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPhanTramLoiQuanLySanPham, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhanTramLoiQuanLySanPham, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPhongCachMguoiMacQuanLySanPham1)
                    .addComponent(cbKieuNguoiMac, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTinhTrang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaLoaiSpQuanLySanPham, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLoaiSanPham, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemPBSP))
                .addGap(54, 54, 54)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoaQuanLySanPham, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnSuaQuanLySanPham, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemQuanLySanPham, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PnDanhSachSanPhamQuanLySanPham.setBackground(new Color(255, 255, 255));
        PnDanhSachSanPhamQuanLySanPham.setBorder(BorderFactory.createTitledBorder(null, "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 24))); // NOI18N

        tbDanhSachSanPham.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Danh mục", "Loại sản phẩm", "Phong cách", "Thương hiệu", "Độ  tuổi", "Tình trạng"
            }
        ));
        spDanhSachSapnPham.setViewportView(tbDanhSachSanPham);

        GroupLayout PnDanhSachSanPhamQuanLySanPhamLayout = new GroupLayout(PnDanhSachSanPhamQuanLySanPham);
        PnDanhSachSanPhamQuanLySanPham.setLayout(PnDanhSachSanPhamQuanLySanPhamLayout);
        PnDanhSachSanPhamQuanLySanPhamLayout.setHorizontalGroup(
            PnDanhSachSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachSapnPham)
        );
        PnDanhSachSanPhamQuanLySanPhamLayout.setVerticalGroup(
            PnDanhSachSanPhamQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachSapnPham, GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pnTimKiemQuanLySanPham.setBackground(new Color(255, 255, 255));
        pnTimKiemQuanLySanPham.setBorder(BorderFactory.createTitledBorder(null, "Tìm Kiếm sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 14))); // NOI18N

        cbTkKieuNguoiMacSp.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        cbTkKieuNguoiMacSp.setModel(new DefaultComboBoxModel<>(new String[] { "Phong cách mặc", " ", " " }));

        cbTkDanhMuc.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        cbTkDanhMuc.setModel(new DefaultComboBoxModel<>(new String[] { "Danh mục", " " }));

        cbTkLoaiSanPham.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        cbTkLoaiSanPham.setModel(new DefaultComboBoxModel<>(new String[] { "Loại sản phẩm", " " }));

        cbTkTinhTrang.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        cbTkTinhTrang.setModel(new DefaultComboBoxModel<>(new String[] { "Tình trạng", " " }));

        cbTkTHuongHieu.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        cbTkTHuongHieu.setModel(new DefaultComboBoxModel<>(new String[] { "Thương hiệu", " " }));

        cbTkDoTuoi.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        cbTkDoTuoi.setModel(new DefaultComboBoxModel<>(new String[] { "Độ tuổi" }));

        jLabel1.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Từ khoá tìm kiếm");

        txtTuKhoaTimKiem.setFont(new Font("Segoe UI", 0, 18)); // NOI18N

        GroupLayout pnTimKiemQuanLySanPhamLayout = new GroupLayout(pnTimKiemQuanLySanPham);
        pnTimKiemQuanLySanPham.setLayout(pnTimKiemQuanLySanPhamLayout);
        pnTimKiemQuanLySanPhamLayout.setHorizontalGroup(
            pnTimKiemQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemQuanLySanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTkDanhMuc, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkLoaiSanPham, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkTinhTrang, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkTHuongHieu, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkDoTuoi, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkKieuNguoiMacSp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoaTimKiem, GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTimKiemQuanLySanPhamLayout.setVerticalGroup(
            pnTimKiemQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemQuanLySanPhamLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnTimKiemQuanLySanPhamLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTkKieuNguoiMacSp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkDanhMuc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkLoaiSanPham, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkTinhTrang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkTHuongHieu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkDoTuoi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, pnTimKiemQuanLySanPhamLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTuKhoaTimKiem, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout pnBGThongTinCaNhanLayout = new GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(PnDanhSachSanPhamQuanLySanPham, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(pnThongTinSanPhamQuanLySanPham, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTimKiemQuanLySanPham, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(PnDanhSachSanPhamQuanLySanPham, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiemQuanLySanPham, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongTinSanPhamQuanLySanPham, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbDialogKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDialogKichThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDialogKichThuocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel PnDanhSachSanPhamQuanLySanPham;
    private JButton btnDialogAnh;
    private JButton btnDialogThemXuong;
    private JButton btnDialogXong;
    private JButton btnSuaQuanLySanPham;
    private JButton btnThemPBSP;
    private JButton btnThemQuanLySanPham;
    private JButton btnXoaQuanLySanPham;
    private JComboBox<String> cbDanhMuc;
    private JComboBox<String> cbDialogKichThuoc;
    private JComboBox<String> cbDialogMauSac;
    private JComboBox<String> cbDoTuoi;
    private JComboBox<String> cbKieuNguoiMac;
    private JComboBox<String> cbLoaiSanPham;
    private JComboBox<String> cbTh;
    private JComboBox<String> cbTinhTrang;
    private JComboBox<String> cbTkDanhMuc;
    private JComboBox<String> cbTkDoTuoi;
    private JComboBox<String> cbTkKieuNguoiMacSp;
    private JComboBox<String> cbTkLoaiSanPham;
    private JComboBox<String> cbTkTHuongHieu;
    private JComboBox<String> cbTkTinhTrang;
    private JDateChooser jDateChooserNgaySanXuat;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel4;
    private JLabel lbDoTuoiQuanLySanPham;
    private JLabel lbHhQuanLySanPham;
    private JLabel lbMaLoaiSpQuanLySanPham;
    private JLabel lbMaSpQuanLySanPham;
    private JLabel lbNgaySanXuatQuanLySanPham;
    private JLabel lbPhanTramLoiQuanLySanPham;
    private JLabel lbPhongCachMguoiMacQuanLySanPham1;
    private JLabel lbTenSpQuanLySanPham;
    private JLabel lbXuatXuQuanLySanPham;
    private JPanel pnBGThongTinCaNhan;
    private JPanel pnDialogAnh;
    private JPanel pnThongTinSanPhamQuanLySanPham;
    private JPanel pnTimKiemQuanLySanPham;
    private JScrollPane spDanhSachSapnPham;
    private JScrollPane spDialogDanhSachPhienBanSanPham;
    private JTable tbDIalogDanhSachCacSanPham;
    private JTable tbDanhSachSanPham;
    private JTextField txtDialogMaSanPham;
    private JTextField txtDialogSoLuong;
    private JTextField txtMaSpQuanLySanPham;
    private JTextField txtPhanTramLoiQuanLySanPham;
    private JTextField txtTenSpQuanLySanPham;
    private JTextField txtTuKhoaTimKiem;
    private JTextField txtXuatXuQuanLySanPham;
    private JDialog winThemPBSP;
    // End of variables declaration//GEN-END:variables
    public JDialog getWinThemPBSP(){return winThemPBSP;}
    public JTable getTbDanhSachSanPham(){
        return tbDanhSachSanPham;
    }
    public JTextField getTxtMaSanPham(){return txtMaSpQuanLySanPham;}
    public JTextField getTxtTenSanPham(){return txtTenSpQuanLySanPham;}
    public JDateChooser getJDateChooserNgaySanXuat(){return jDateChooserNgaySanXuat;}
    public JTextField getTxtXuatXu(){return txtXuatXuQuanLySanPham;}
    public JComboBox getCbDoTuoi(){return cbDoTuoi;}
    public JComboBox getCbTinhTrang(){return cbTinhTrang;}
    public JComboBox getDanhMuc(){return cbDanhMuc;}
    public JComboBox getCbLoai(){return cbLoaiSanPham;}
    public JComboBox getCbThuongHieu(){return cbTh;}
//    public JComboBox getCbMauSac(){return cbMauSac;}
//    public JTextField getTxtKichThuoc(){return txtKichThuocQuanLySanPham;}
    public JTextField getTxtPhamTramLoi(){return txtPhanTramLoiQuanLySanPham;}
    public JComboBox getCbKieuNguoiMac(){return cbKieuNguoiMac;}
//    public JPanel getPnImgSanPham(){return pnImgSanPham;}
    public JButton getButtonThem(){return btnThemQuanLySanPham;}
    public JButton getButtonSua(){return btnSuaQuanLySanPham;}
    public JButton getButtonXoa(){return btnXoaQuanLySanPham;}
//    public JTextField getTxtSoLuongSanPham(){return txtSoLuongSanPham;}
//    public JButton getBtnThemAnhSanPham(){return btnThemAnhSanPham;}
    public JTextField getTxtTuKhoaTimKiem(){return txtTuKhoaTimKiem;}
    public JComboBox getCbTkDanhMuc(){return  cbTkDanhMuc;}
    public JComboBox getCbTkLoaiSanPham(){return cbTkLoaiSanPham;}
    public JComboBox getCbTkTinhTrang(){return cbTkTinhTrang;}
    public JComboBox getCbTkThuongHieu(){return cbTkTHuongHieu;}
    public JComboBox getCbTkDoTuoi(){return cbTkDoTuoi;}
    public JComboBox getCbTkPhongCachMac(){return cbTkKieuNguoiMacSp;}
    public JButton getBtnThemPBSP(){return btnThemPBSP;}
    public JComboBox getCbDialogKichThuoc(){return cbDialogKichThuoc;}
    public JComboBox getCbDialogMauSac(){return cbDialogMauSac;}
    public JTable getTbDialogDanhSachCacSanPham(){return tbDIalogDanhSachCacSanPham;}
    public JPanel getPnDialogAnh(){return pnDialogAnh;}
    public JTextField getTxtDialogMaSanPham(){return txtDialogMaSanPham;}
    public JTextField getTxtDialogSoLuong(){return txtDialogSoLuong;}
    public JButton getBtnDialogAnh(){return btnDialogAnh;}
    public JButton getBtnDialogThemXuong(){return btnDialogThemXuong;}
    public JButton getBtnDialogXong(){return btnDialogXong;}

}
