/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;
//import dev.skyherobrine.app.controllers.dashboardui.QuanLyHoaDon.HoaDonController;
import dev.skyherobrine.app.controllers.dashboardui.QuanLyHoaDon.HoaDonController;
import lombok.Getter;

import javax.swing.*;

/**
 *
 * @author Virtue Nguyen
 */
public class QuanLyHoaDon extends JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public QuanLyHoaDon() {
        initComponents();
        HoaDonController controller = new HoaDonController(this);
        txtHoaDon.setEnabled(false);
        txtNgayLap.setEnabled(false);
        txtTenNhanVien.setEnabled(false);
        txtKhachHang.setEnabled(false);
        txtKhachHang1.setEnabled(false);
        txtKhachHang2.setEnabled(false);
        tbDanhSachHoaDon.addMouseListener(controller);
        btnInHoaDon.addActionListener(controller);
        btnXuatHoaDon.addActionListener(controller);
        txtTuKhoaTimKiem.addKeyListener(controller);
        jDateChooserNgayLapHoaDon.addPropertyChangeListener("date", controller);

        setDoubleBuffered(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
//     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBGThongTinCaNhan = new JPanel();
        pnDanhSachHoaDon = new JPanel();
        spDanhSachHoaDon = new JScrollPane();
        tbDanhSachHoaDon = new JTable();
        pnTimKiemHoaDon = new JPanel();
        cbTkCaLamViec = new JComboBox<>();
        txtTuKhoaTimKiem = new JTextField();
        btnXuatHoaDon = new JButton();
        jDateChooserNgayLapHoaDon = new JDateChooser();
        jLabel1 = new JLabel();
        lbTuKhoaTimKiem = new JLabel();
        jPanel1 = new JPanel();
        pnHoaDon = new JPanel();
        txtTenNhanVien = new JTextField();
        lbHoaDon1 = new JLabel();
        lbTenNhanVien = new JLabel();
        txtHoaDon = new JTextField();
        lbNgayLap = new JLabel();
        txtNgayLap = new JTextField();
        lbTenKhachHang = new JLabel();
        txtKhachHang = new JTextField();
        lbTien = new JLabel();
        txtKhachHang1 = new JTextField();
        lbTienPhaiTra = new JLabel();
        txtKhachHang2 = new JTextField();
        btnInHoaDon = new JButton();
        lbGhiChu = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnDanhSachHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachHoaDon.setBorder(BorderFactory.createTitledBorder(null, "Danh Sách hoá đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        tbDanhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "STT", "Mã hóa đơn", "Ngày lập", "Nhân viên"
            }
        ));
        spDanhSachHoaDon.setViewportView(tbDanhSachHoaDon);

        GroupLayout pnDanhSachHoaDonLayout = new GroupLayout(pnDanhSachHoaDon);
        pnDanhSachHoaDon.setLayout(pnDanhSachHoaDonLayout);
        pnDanhSachHoaDonLayout.setHorizontalGroup(
            pnDanhSachHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhSachHoaDonLayout.createSequentialGroup()
                .addComponent(spDanhSachHoaDon, GroupLayout.PREFERRED_SIZE, 1020, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnDanhSachHoaDonLayout.setVerticalGroup(
            pnDanhSachHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachHoaDon, GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );

        pnTimKiemHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnTimKiemHoaDon.setBorder(BorderFactory.createTitledBorder(null, "Tìm Kiếm hoá đơn ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        cbTkCaLamViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkCaLamViec.setModel(new DefaultComboBoxModel<>(new String[] { "Ca làm việc", " " }));

        txtTuKhoaTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTuKhoaTimKiem.setToolTipText("");

        btnXuatHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXuatHoaDon.setText("xuất hoá đơn");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ngày lập hoá đơn:");

        lbTuKhoaTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTuKhoaTimKiem.setText("Từ khoá tìm kiếm:");

        GroupLayout pnTimKiemHoaDonLayout = new GroupLayout(pnTimKiemHoaDon);
        pnTimKiemHoaDon.setLayout(pnTimKiemHoaDonLayout);
        pnTimKiemHoaDonLayout.setHorizontalGroup(
            pnTimKiemHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserNgayLapHoaDon, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(cbTkCaLamViec, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(lbTuKhoaTimKiem)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoaTimKiem, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatHoaDon)
                .addGap(146, 146, 146))
        );
        pnTimKiemHoaDonLayout.setVerticalGroup(
            pnTimKiemHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimKiemHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTuKhoaTimKiem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTkCaLamViec, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserNgayLapHoaDon, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, pnTimKiemHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTuKhoaTimKiem, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXuatHoaDon, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        pnHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        txtTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhanVienActionPerformed(evt);
            }
        });

        lbHoaDon1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHoaDon1.setText("Mã hóa đơn: ");

        lbTenNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTenNhanVien.setText("Nhân viên bán hàng: ");

        txtHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoaDonActionPerformed(evt);
            }
        });

        lbNgayLap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgayLap.setText("Ngày lập hóa đơn: ");

        txtNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayLapActionPerformed(evt);
            }
        });

        lbTenKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTenKhachHang.setText("Khách hàng: ");

        txtKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachHangActionPerformed(evt);
            }
        });

        lbTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTien.setText("Số tiền khách trả:");

        txtKhachHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachHang1ActionPerformed(evt);
            }
        });

        lbTienPhaiTra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTienPhaiTra.setText("Tổng tiền:");

        txtKhachHang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachHang2ActionPerformed(evt);
            }
        });

        btnInHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInHoaDon.setText("In hoá đơn");

        lbGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGhiChu.setText("Ghi chú:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        GroupLayout pnHoaDonLayout = new GroupLayout(pnHoaDon);
        pnHoaDon.setLayout(pnHoaDonLayout);
        pnHoaDonLayout.setHorizontalGroup(
            pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbHoaDon1)
                    .addGroup(pnHoaDonLayout.createSequentialGroup()
                        .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenNhanVien)
                            .addComponent(lbNgayLap)
                            .addComponent(lbTenKhachHang)
                            .addComponent(lbTien)
                            .addComponent(lbTienPhaiTra)
                            .addComponent(lbGhiChu))
                        .addGap(18, 18, 18)
                        .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 254, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhachHang2, GroupLayout.PREFERRED_SIZE, 254, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhachHang1, GroupLayout.PREFERRED_SIZE, 254, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhachHang, GroupLayout.PREFERRED_SIZE, 254, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayLap, GroupLayout.PREFERRED_SIZE, 254, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNhanVien, GroupLayout.PREFERRED_SIZE, 254, GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnHoaDonLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnInHoaDon)))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, pnHoaDonLayout.createSequentialGroup()
                    .addContainerGap(232, Short.MAX_VALUE)
                    .addComponent(txtHoaDon, GroupLayout.PREFERRED_SIZE, 252, GroupLayout.PREFERRED_SIZE)
                    .addGap(121, 121, 121)))
        );
        pnHoaDonLayout.setVerticalGroup(
            pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lbHoaDon1)
                .addGap(38, 38, 38)
                .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenNhanVien)
                    .addComponent(txtTenNhanVien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgayLap)
                    .addComponent(txtNgayLap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenKhachHang)
                    .addComponent(txtKhachHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTien)
                    .addComponent(txtKhachHang1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTienPhaiTra)
                    .addComponent(txtKhachHang2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnHoaDonLayout.createSequentialGroup()
                        .addComponent(lbGhiChu)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInHoaDon, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(pnHoaDonLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnHoaDonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(pnHoaDonLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(txtHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(777, Short.MAX_VALUE)))
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnHoaDon, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout pnBGThongTinCaNhanLayout = new GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnTimKiemHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnDanhSachHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(pnDanhSachHoaDon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiemHoaDon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhanVienActionPerformed

    private void txtHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoaDonActionPerformed

    private void txtNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayLapActionPerformed

    private void txtKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachHangActionPerformed

    private void txtKhachHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachHang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachHang1ActionPerformed

    private void txtKhachHang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachHang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachHang2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    @Getter
    private JButton btnInHoaDon;
    @Getter
    private JButton btnXuatHoaDon;
    @Getter
    private JComboBox<String> cbTkCaLamViec;
    @Getter
    private JDateChooser jDateChooserNgayLapHoaDon;
    private JLabel jLabel1;
    @Getter
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;
    private JLabel lbGhiChu;
    private JLabel lbHoaDon1;
    private JLabel lbNgayLap;
    private JLabel lbTenKhachHang;
    private JLabel lbTenNhanVien;
    private JLabel lbTien;
    private JLabel lbTienPhaiTra;
    private JLabel lbTuKhoaTimKiem;
    private JPanel pnBGThongTinCaNhan;
    private JPanel pnDanhSachHoaDon;
    @Getter
    private JPanel pnHoaDon;
    private JPanel pnTimKiemHoaDon;
    private JScrollPane spDanhSachHoaDon;
    @Getter
    private JTable tbDanhSachHoaDon;
    @Getter
    private JTextField txtHoaDon;
    @Getter
    private JTextField txtKhachHang;
    @Getter
    private JTextField txtKhachHang1;
    @Getter
    private JTextField txtKhachHang2;
    @Getter
    private JTextField txtNgayLap;
    @Getter
    private JTextField txtTenNhanVien;
    @Getter
    private JTextField txtTuKhoaTimKiem;
    // End of variables declaration//GEN-END:variables
}
