/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;


import com.toedter.calendar.JDateChooser;
import dev.skyherobrine.app.controllers.dashboardui.order.NhapHangController;
//import dev.skyherobrine.app.controllers.dashboardui.order.NhapHangController;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author Virtue Nguyen
 */
public class QuanLyNhapHang extends JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public QuanLyNhapHang() {
        initComponents();

        NhapHangController controller = new NhapHangController(this);

        controller.loadPhieuNhap();
        controller.loadComboBoxPhanTimKiem();
        tbDanhSachPheiNhap.addMouseListener(controller);
        tbDanhSachSpTrongGioHang.addMouseListener(controller);
        tblChonPBSP.addMouseListener(controller);

        menuSPNhap.add(pnTimSPNhap);
        menuNCCNhap.add(pnNCCNhap);

        listSPNhap.addKeyListener(controller);
        listNCCNhap.addKeyListener(controller);

        btnThemPhieuNhap.addActionListener(controller);
        btnSuaPhieuNhap.addActionListener(controller);
        btnXuatFile.addActionListener(controller);

        txtTimKiemSanPhamNhap.addKeyListener(controller);
        txtNhaCungCap.addKeyListener(controller);

        tbDanhSachSpTrongGioHang.getModel().addTableModelListener(controller);

        cbTkNhaCungCap.addActionListener(controller);
        cbTkTinhTrang.addActionListener(controller);
        jDateChooserTkNgayLapPhieu.addPropertyChangeListener(controller);
        jDateChooserTkNgayHenGiao.addPropertyChangeListener(controller);

        btnChonXongPBSP.addActionListener(controller);


        tbDanhSachSpTrongGioHang.getColumnModel().getColumn(7).setCellRenderer(new dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellRender());
        tbDanhSachSpTrongGioHang.getColumnModel().getColumn(7).setCellEditor(new dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellEditor(controller));


        tbDanhSachSpTrongGioHang.getColumnModel().getColumn(3).setCellRenderer(new dev.skyherobrine.app.views.dashboard.component.nutChon.TableActionCellRender());
        tbDanhSachSpTrongGioHang.getColumnModel().getColumn(3).setCellEditor(new dev.skyherobrine.app.views.dashboard.component.nutChon.TableActionCellEditor(controller));
        if(tbDanhSachSpTrongGioHang.isEditing()){
            tbDanhSachSpTrongGioHang.getCellEditor().stopCellEditing();
        }
        btnTrangThaiPhieu.addActionListener(controller);
        btnTrangThaiPhieu.setVisible(false);
        cbkDangLayHang.setEnabled(false);
        cbkDuyet.setEnabled(false);
        cbkHoanThanh.setEnabled(false);
        txtDiaChiCuaHang.setEnabled(false);
        txtDienThoaiCuaHang.setEnabled(false);
        txtEmailCUaHang.setEnabled(false);
        txtDiaChi.setEnabled(false);
        txtEmailNhaCungCap.setEnabled(false);
        txtNgayLap.setEnabled(false);
        txtTinhTrangPhieuNhap.setEnabled(false);
        txtTongTienSanPham.setEnabled(false);
        txtGhiChu.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTimSPNhap = new JPanel();
        jScrollPane1 = new JScrollPane();
        listSPNhap = new JList<>();
        menuSPNhap = new JPopupMenu();
        pnNCCNhap = new JPanel();
        jScrollPane2 = new JScrollPane();
        listNCCNhap = new JList<>();
        menuNCCNhap = new JPopupMenu();
        winPBSP = new JDialog();
        pnChonPBSP = new JPanel();
        lblSanPhamFrmChonPBSP = new JLabel();
        txtMaSPBangChonPBSP = new JTextField();
        jPanel3 = new JPanel();
        jScrollPane3 = new JScrollPane();
        tblChonPBSP = new JTable();
        btnChonXongPBSP = new JButton();
        pnBGThongTinCaNhan = new JPanel();
        pnThongTinNhapHang = new JPanel();
        pnButton = new JPanel();
        btnThemPhieuNhap = new JButton();
        btnSuaPhieuNhap = new JButton();
        btnXuatFile = new JButton();
        txtTimKiemSanPhamNhap = new JTextField();
        pnDanhSach = new JPanel();
        spDanhSachSpTrongGioHang = new JScrollPane();
        tbDanhSachSpTrongGioHang = new JTable();
        pnDanhSachPhieuNhap = new JPanel();
        spDanhSachPhieuNhap = new JScrollPane();
        tbDanhSachPheiNhap = new JTable();
        pnTimKiemPhieuNhap = new JPanel();
        cbTkNhaCungCap = new JComboBox<>();
        cbTkTinhTrang = new JComboBox<>();
        jLabel1 = new JLabel();
        jDateChooserTkNgayLapPhieu = new JDateChooser();
        jLabel2 = new JLabel();
        jDateChooserTkNgayHenGiao = new JDateChooser();
        txtTkPhieuNhap = new JTextField();
        jLabel3 = new JLabel();
        jPanel1 = new JPanel();
        pnThongTinCuaHang = new JPanel();
        lbDiaChiCuaHang = new JLabel();
        lbDienThoaiCuaHang = new JLabel();
        jLabel4 = new JLabel();
        txtDienThoaiCuaHang = new JTextField();
        txtEmailCUaHang = new JTextField();
        txtDiaChiCuaHang = new JTextField();
        pnTHongTinNhaCungCap = new JPanel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel8 = new JLabel();
        txtNhaCungCap = new JTextField();
        txtDiaChi = new JTextField();
        txtEmailNhaCungCap = new JTextField();
        jPanel2 = new JPanel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jDateChooserNgayHenGiao = new JDateChooser();
        txtTongTienSanPham = new JTextField();
        jLabel11 = new JLabel();
        txtTinhTrangPhieuNhap = new JTextField();
        jLabel12 = new JLabel();
        txtNgayLap = new JTextField();
        jLabel13 = new JLabel();
        txtMaPhieu = new JTextField();
        jLabel7 = new JLabel();
        txtGhiChu = new JTextField();
        cbkDuyet = new JCheckBox();
        cbkDangLayHang = new JCheckBox();
        lblChoDuyet = new JLabel();
        lblNhapKho = new JLabel();
        lblHoanThanh = new JLabel();
        cbkHoanThanh = new JCheckBox();
        lblNgayfDuyet = new JLabel();
        lblNgayChLayHang = new JLabel();
        lblNgayHoanThanh = new JLabel();
        btnTrangThaiPhieu = new JButton();

        pnTimSPNhap.setFocusable(false);

        listSPNhap.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listSPNhap);

        GroupLayout pnTimSPNhapLayout = new GroupLayout(pnTimSPNhap);
        pnTimSPNhap.setLayout(pnTimSPNhapLayout);
        pnTimSPNhapLayout.setHorizontalGroup(
            pnTimSPNhapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
        pnTimSPNhapLayout.setVerticalGroup(
            pnTimSPNhapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        menuSPNhap.setFocusable(false);

        listNCCNhap.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listNCCNhap);

        GroupLayout pnNCCNhapLayout = new GroupLayout(pnNCCNhap);
        pnNCCNhap.setLayout(pnNCCNhapLayout);
        pnNCCNhapLayout.setHorizontalGroup(
            pnNCCNhapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        pnNCCNhapLayout.setVerticalGroup(
            pnNCCNhapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        menuNCCNhap.setFocusable(false);

        winPBSP.setModal(true);
        winPBSP.setSize(new Dimension(600, 400));

        pnChonPBSP.setFocusable(false);
        pnChonPBSP.setRequestFocusEnabled(false);

        lblSanPhamFrmChonPBSP.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblSanPhamFrmChonPBSP.setText("Sản phẩm:");

        txtMaSPBangChonPBSP.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        txtMaSPBangChonPBSP.setEnabled(false);

        jPanel3.setBorder(BorderFactory.createTitledBorder(null, "Các phiên bản sản phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 14))); // NOI18N

        tblChonPBSP.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaPBSP", "Màu sắc", "Kích thước", "Số lượng", ""
            }
        ) {
            Class[] types = new Class [] {
                Object.class, Object.class, Object.class, Object.class, Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblChonPBSP.setRowHeight(40);
        jScrollPane3.setViewportView(tblChonPBSP);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnChonXongPBSP.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        btnChonXongPBSP.setText("Xong");
        btnChonXongPBSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonXongPBSPActionPerformed(evt);
            }
        });

        GroupLayout pnChonPBSPLayout = new GroupLayout(pnChonPBSP);
        pnChonPBSP.setLayout(pnChonPBSPLayout);
        pnChonPBSPLayout.setHorizontalGroup(
            pnChonPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnChonPBSPLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnChonPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnChonPBSPLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSanPhamFrmChonPBSP, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaSPBangChonPBSP, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(GroupLayout.Alignment.TRAILING, pnChonPBSPLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChonXongPBSP, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnChonPBSPLayout.setVerticalGroup(
            pnChonPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnChonPBSPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnChonPBSPLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSanPhamFrmChonPBSP, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSPBangChonPBSP, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChonXongPBSP, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        GroupLayout winPBSPLayout = new GroupLayout(winPBSP.getContentPane());
        winPBSP.getContentPane().setLayout(winPBSPLayout);
        winPBSPLayout.setHorizontalGroup(
            winPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
            .addGroup(winPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(winPBSPLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnChonPBSP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        winPBSPLayout.setVerticalGroup(
            winPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(winPBSPLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(winPBSPLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnChonPBSP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setPreferredSize(new Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new Dimension(1651, 1000));

        pnThongTinNhapHang.setBackground(new Color(255, 255, 255));
        pnThongTinNhapHang.setBorder(BorderFactory.createTitledBorder(null, "Thông tin nhập hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 24))); // NOI18N
        pnThongTinNhapHang.setFont(new Font("Segoe UI", 1, 18)); // NOI18N

        pnButton.setBackground(new Color(255, 255, 255));

        btnThemPhieuNhap.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnThemPhieuNhap.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/plus.png"))); // NOI18N
        btnThemPhieuNhap.setText("Thêm phiếu nhập");

        btnSuaPhieuNhap.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnSuaPhieuNhap.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/edit.png"))); // NOI18N
        btnSuaPhieuNhap.setText("Sửa phiếu nhập");

        btnXuatFile.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnXuatFile.setIcon(new ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/remove.png"))); // NOI18N
        btnXuatFile.setText("Xóa phiếu chờ");

        GroupLayout pnButtonLayout = new GroupLayout(pnButton);
        pnButton.setLayout(pnButtonLayout);
        pnButtonLayout.setHorizontalGroup(
            pnButtonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnThemPhieuNhap, GroupLayout.PREFERRED_SIZE, 203, GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(btnSuaPhieuNhap)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXuatFile, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        pnButtonLayout.setVerticalGroup(
            pnButtonLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnButtonLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnButtonLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemPhieuNhap, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnSuaPhieuNhap, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXuatFile, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtTimKiemSanPhamNhap.setFont(new Font("Segoe UI", 0, 14)); // NOI18N

        tbDanhSachSpTrongGioHang.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "PBSP", "Số lượng", "Đơn giá", "Thành tiền", ""
            }
        ));
        tbDanhSachSpTrongGioHang.setRowHeight(40);
        spDanhSachSpTrongGioHang.setViewportView(tbDanhSachSpTrongGioHang);
        if (tbDanhSachSpTrongGioHang.getColumnModel().getColumnCount() > 0) {
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(0).setMaxWidth(40);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(1).setPreferredWidth(160);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(1).setMaxWidth(160);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(2).setPreferredWidth(320);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(2).setMaxWidth(320);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(3).setPreferredWidth(120);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(3).setMaxWidth(120);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(4).setPreferredWidth(80);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(4).setMaxWidth(80);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(7).setPreferredWidth(60);
            tbDanhSachSpTrongGioHang.getColumnModel().getColumn(7).setMaxWidth(60);
        }

        GroupLayout pnDanhSachLayout = new GroupLayout(pnDanhSach);
        pnDanhSach.setLayout(pnDanhSachLayout);
        pnDanhSachLayout.setHorizontalGroup(
            pnDanhSachLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachSpTrongGioHang)
        );
        pnDanhSachLayout.setVerticalGroup(
            pnDanhSachLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachSpTrongGioHang, GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        GroupLayout pnThongTinNhapHangLayout = new GroupLayout(pnThongTinNhapHang);
        pnThongTinNhapHang.setLayout(pnThongTinNhapHangLayout);
        pnThongTinNhapHangLayout.setHorizontalGroup(
            pnThongTinNhapHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnThongTinNhapHangLayout.createSequentialGroup()
                .addComponent(txtTimKiemSanPhamNhap, GroupLayout.PREFERRED_SIZE, 423, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnDanhSach, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnThongTinNhapHangLayout.setVerticalGroup(
            pnThongTinNhapHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnThongTinNhapHangLayout.createSequentialGroup()
                .addComponent(txtTimKiemSanPhamNhap, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDanhSach, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        pnDanhSachPhieuNhap.setBackground(new Color(255, 255, 255));
        pnDanhSachPhieuNhap.setBorder(BorderFactory.createTitledBorder(null, "Danh Sách phiếu nhập", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 24))); // NOI18N

        tbDanhSachPheiNhap.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Nhà cung cấp", "Ngày lập", "Ngày gia hạn", "Tình trạng"
            }
        ));
        tbDanhSachPheiNhap.setRowHeight(40);
        spDanhSachPhieuNhap.setViewportView(tbDanhSachPheiNhap);

        GroupLayout pnDanhSachPhieuNhapLayout = new GroupLayout(pnDanhSachPhieuNhap);
        pnDanhSachPhieuNhap.setLayout(pnDanhSachPhieuNhapLayout);
        pnDanhSachPhieuNhapLayout.setHorizontalGroup(
            pnDanhSachPhieuNhapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachPhieuNhap, GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
        );
        pnDanhSachPhieuNhapLayout.setVerticalGroup(
            pnDanhSachPhieuNhapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachPhieuNhap, GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pnTimKiemPhieuNhap.setBackground(new Color(255, 255, 255));
        pnTimKiemPhieuNhap.setBorder(BorderFactory.createTitledBorder(null, "Tìm Kiếm phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 14))); // NOI18N

        cbTkNhaCungCap.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        cbTkNhaCungCap.setModel(new DefaultComboBoxModel<>(new String[] { "Nhà cung cấp", " " }));

        cbTkTinhTrang.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        cbTkTinhTrang.setModel(new DefaultComboBoxModel<>(new String[] { "Tình trạng", " " }));

        jLabel1.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ngày lập phiếu:");

        jLabel2.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Ngày hẹn giao:");

        jLabel3.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Từ khoá tìm kiếm:");

        GroupLayout pnTimKiemPhieuNhapLayout = new GroupLayout(pnTimKiemPhieuNhap);
        pnTimKiemPhieuNhap.setLayout(pnTimKiemPhieuNhapLayout);
        pnTimKiemPhieuNhapLayout.setHorizontalGroup(
            pnTimKiemPhieuNhapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTkNhaCungCap, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTkTinhTrang, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTkNgayLapPhieu, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTkNgayHenGiao, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTkPhieuNhap, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE))
        );
        pnTimKiemPhieuNhapLayout.setVerticalGroup(
            pnTimKiemPhieuNhapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemPhieuNhapLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTimKiemPhieuNhapLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTkPhieuNhap)
                    .addComponent(jDateChooserTkNgayLapPhieu, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.LEADING, pnTimKiemPhieuNhapLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTkNhaCungCap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbTkTinhTrang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jDateChooserTkNgayHenGiao, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new Color(255, 255, 255));

        pnThongTinCuaHang.setBackground(new Color(255, 255, 255));
        pnThongTinCuaHang.setBorder(BorderFactory.createTitledBorder(null, "Thông tin cửa hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 18))); // NOI18N

        lbDiaChiCuaHang.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbDiaChiCuaHang.setText("Địa chỉ:");

        lbDienThoaiCuaHang.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lbDienThoaiCuaHang.setText("Điện thoại:");

        jLabel4.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Email:");

        GroupLayout pnThongTinCuaHangLayout = new GroupLayout(pnThongTinCuaHang);
        pnThongTinCuaHang.setLayout(pnThongTinCuaHangLayout);
        pnThongTinCuaHangLayout.setHorizontalGroup(
            pnThongTinCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinCuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbDienThoaiCuaHang)
                    .addComponent(lbDiaChiCuaHang)
                    .addComponent(jLabel4))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtDienThoaiCuaHang)
                    .addComponent(txtEmailCUaHang)
                    .addComponent(txtDiaChiCuaHang))
                .addContainerGap())
        );
        pnThongTinCuaHangLayout.setVerticalGroup(
            pnThongTinCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinCuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDiaChiCuaHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiaChiCuaHang, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDienThoaiCuaHang, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lbDienThoaiCuaHang, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinCuaHangLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmailCUaHang, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTHongTinNhaCungCap.setBackground(new Color(255, 255, 255));
        pnTHongTinNhaCungCap.setBorder(BorderFactory.createTitledBorder(null, "Thông tin nhà cung cấp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 18))); // NOI18N

        jLabel5.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nhà cung cấp:");

        jLabel6.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Địa chỉ:");

        jLabel8.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Email:");

        GroupLayout pnTHongTinNhaCungCapLayout = new GroupLayout(pnTHongTinNhaCungCap);
        pnTHongTinNhaCungCap.setLayout(pnTHongTinNhaCungCapLayout);
        pnTHongTinNhaCungCapLayout.setHorizontalGroup(
            pnTHongTinNhaCungCapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTHongTinNhaCungCapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTHongTinNhaCungCapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTHongTinNhaCungCapLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDiaChi)
                    .addComponent(txtNhaCungCap, GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailNhaCungCap, GroupLayout.PREFERRED_SIZE, 221, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnTHongTinNhaCungCapLayout.setVerticalGroup(
            pnTHongTinNhaCungCapLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnTHongTinNhaCungCapLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTHongTinNhaCungCapLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNhaCungCap)
                    .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinNhaCungCapLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiaChi)
                    .addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinNhaCungCapLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailNhaCungCap, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(290, 290, 290))
        );

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setBorder(BorderFactory.createTitledBorder(null, "Thông tin phiếu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 18))); // NOI18N

        jLabel9.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Ngày lập:");

        jLabel10.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Ngày hẹn giao");

        jLabel11.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Tổng tiền sản phẩm:");

        jLabel12.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tình trạng:");

        jLabel13.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Mã phiếu:");

        jLabel7.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Ghi chú:");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtGhiChu)
                    .addComponent(txtMaPhieu)
                    .addComponent(txtTinhTrangPhieuNhap)
                    .addComponent(txtTongTienSanPham)
                    .addComponent(jDateChooserNgayHenGiao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayLap))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtMaPhieu))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayLap, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserNgayHenGiao, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTienSanPham, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTinhTrangPhieuNhap, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtGhiChu))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbkDuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkDuyetActionPerformed(evt);
            }
        });

        lblChoDuyet.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblChoDuyet.setText("Duyệt");
        lblChoDuyet.setPreferredSize(new Dimension(60, 20));

        lblNhapKho.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblNhapKho.setText("Nhập kho");

        lblHoanThanh.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblHoanThanh.setText("Hoàn thành");

        cbkHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkHoanThanhActionPerformed(evt);
            }
        });

        lblNgayfDuyet.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayfDuyet.setPreferredSize(new Dimension(44, 20));

        lblNgayChLayHang.setFont(new Font("Segoe UI", 0, 14)); // NOI18N

        lblNgayHoanThanh.setFont(new Font("Segoe UI", 0, 14)); // NOI18N

        btnTrangThaiPhieu.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnTrangThaiPhieu.setIcon(new ImageIcon(getClass().getResource("/img/imgIconQuanLyNhapHang/duyet.png"))); // NOI18N
        btnTrangThaiPhieu.setText("Duyệt");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnThongTinCuaHang, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnTHongTinNhaCungCap, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNhapKho)
                        .addGap(88, 88, 88)
                        .addComponent(lblHoanThanh)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayfDuyet, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbkDuyet))
                    .addComponent(lblChoDuyet, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(lblNgayChLayHang, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblNgayHoanThanh, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbkDangLayHang)
                        .addGap(135, 135, 135)
                        .addComponent(cbkHoanThanh)
                        .addGap(58, 58, 58))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnTrangThaiPhieu, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnThongTinCuaHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTHongTinNhaCungCap, GroupLayout.PREFERRED_SIZE, 211, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChoDuyet, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNhapKho, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoanThanh))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(cbkDangLayHang)
                    .addComponent(cbkDuyet)
                    .addComponent(cbkHoanThanh))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayfDuyet, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayChLayHang, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayHoanThanh, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangThaiPhieu, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        GroupLayout pnBGThongTinCaNhanLayout = new GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnThongTinNhapHang, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnTimKiemPhieuNhap, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnDanhSachPhieuNhap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnDanhSachPhieuNhap, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiemPhieuNhap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongTinNhapHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonXongPBSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonXongPBSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChonXongPBSPActionPerformed

    private void cbkDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkDuyetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkDuyetActionPerformed

    private void cbkHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkHoanThanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkHoanThanhActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnChonXongPBSP;
    private JButton btnSuaPhieuNhap;
    private JButton btnThemPhieuNhap;
    private JButton btnTrangThaiPhieu;
    private JButton btnXuatFile;
    private JComboBox<String> cbTkNhaCungCap;
    private JComboBox<String> cbTkTinhTrang;
    private JCheckBox cbkDangLayHang;
    private JCheckBox cbkDuyet;
    private JCheckBox cbkHoanThanh;
    private JDateChooser jDateChooserNgayHenGiao;
    private JDateChooser jDateChooserTkNgayHenGiao;
    private JDateChooser jDateChooserTkNgayLapPhieu;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JLabel lbDiaChiCuaHang;
    private JLabel lbDienThoaiCuaHang;
    private JLabel lblChoDuyet;
    private JLabel lblHoanThanh;
    private JLabel lblNgayChLayHang;
    private JLabel lblNgayHoanThanh;
    private JLabel lblNgayfDuyet;
    private JLabel lblNhapKho;
    private JLabel lblSanPhamFrmChonPBSP;
    private JList<String> listNCCNhap;
    private JList<String> listSPNhap;
    private JPopupMenu menuNCCNhap;
    private JPopupMenu menuSPNhap;
    private JPanel pnBGThongTinCaNhan;
    private JPanel pnButton;
    private JPanel pnChonPBSP;
    private JPanel pnDanhSach;
    private JPanel pnDanhSachPhieuNhap;
    private JPanel pnNCCNhap;
    private JPanel pnTHongTinNhaCungCap;
    private JPanel pnThongTinCuaHang;
    private JPanel pnThongTinNhapHang;
    private JPanel pnTimKiemPhieuNhap;
    private JPanel pnTimSPNhap;
    private JScrollPane spDanhSachPhieuNhap;
    private JScrollPane spDanhSachSpTrongGioHang;
    private JTable tbDanhSachPheiNhap;
    private JTable tbDanhSachSpTrongGioHang;
    private JTable tblChonPBSP;
    private JTextField txtDiaChi;
    private JTextField txtDiaChiCuaHang;
    private JTextField txtDienThoaiCuaHang;
    private JTextField txtEmailCUaHang;
    private JTextField txtEmailNhaCungCap;
    private JTextField txtGhiChu;
    private JTextField txtMaPhieu;
    private JTextField txtMaSPBangChonPBSP;
    private JTextField txtNgayLap;
    private JTextField txtNhaCungCap;
    private JTextField txtTimKiemSanPhamNhap;
    private JTextField txtTinhTrangPhieuNhap;
    private JTextField txtTkPhieuNhap;
    private JTextField txtTongTienSanPham;
    private JDialog winPBSP;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtMaPhieuNhap(){return txtMaPhieu;}
    public JTable getTbDanhSachPheiNhap() {return tbDanhSachPheiNhap;}
    public JTable getTbDanhSachSpTrongGioHang(){return  tbDanhSachSpTrongGioHang;}
    public JTextField getTxtNhaCungCap(){return txtNhaCungCap;}
    public JTextField getTxtDiaChi(){return txtDiaChi;}
    public JTextField getTxtEmailNhaCungCap(){return txtEmailNhaCungCap;}
    public JTextField getTxtNgayLapPhieu(){return txtNgayLap;}
    public JDateChooser getjDateChooserNgayHenGiao(){return jDateChooserNgayHenGiao;}
    public JTextField getTxtTongTienSanPham(){return txtTongTienSanPham;}
    public JTextField getTxtTimKiemSanPhamNhap(){return txtTimKiemSanPhamNhap;}
    public JList getListSPNhap(){return listSPNhap;}
    public JList getListNCCNhap(){return listNCCNhap;}
    public JPopupMenu getMenuSPNhap(){return menuSPNhap;}
    public JPopupMenu getMenuNCCNhap(){return menuNCCNhap;}
    public JButton getBtnThemPhieuNhap(){return btnThemPhieuNhap;}
    public JButton getBtnSuaPhieuNhap(){return btnSuaPhieuNhap;}
    public JButton getBtnXuatFile(){return btnXuatFile;}
    public JComboBox getCbTkNhaCungCap(){return cbTkNhaCungCap;}
    public JComboBox getCbTkTinhTrang(){return cbTkTinhTrang;}
    public JDateChooser getjDateChooserTkNgayLapPhieu(){return jDateChooserTkNgayLapPhieu;}
    public JDateChooser getjDateChooserTkNgayHenGiao(){return jDateChooserTkNgayHenGiao;}
    public JTextField getTxtTkPhieuNhap(){return txtTkPhieuNhap;}
    public JTextField getTxtDiaChiCuaHang(){return txtDiaChiCuaHang;}
    public JTextField getTxtDienThoaiCuaHang(){return txtDienThoaiCuaHang;}
    public JTextField getTxtEmailCUaHang(){return txtEmailCUaHang;}
    public JTextField getTxtTinhTrangPhieuNhap(){return txtTinhTrangPhieuNhap;}
    public JTextField getTxtGhiChu(){return txtGhiChu;}
    public JDialog getWinPBSP(){return winPBSP;}
    public JTextField getTxtMaSPBangChonPBSP(){return txtMaSPBangChonPBSP;}
    public JTable getTblChonPBSP(){return tblChonPBSP;}
    public JButton getBtnChonXongPBSP(){return btnChonXongPBSP;}
    public JButton getBtnTrangThaiPhieu(){return btnTrangThaiPhieu;}
    public JCheckBox getCbkDuyet(){return cbkDuyet;}
    public  JCheckBox getCbkDangLayHang(){return cbkDangLayHang;}
    public JCheckBox getCbkHoanThanh(){return cbkHoanThanh;}
    public JLabel getLblNgayfDuyet(){return lblNgayfDuyet;}
    public JLabel getLblNgayChLayHang(){return lblNgayChLayHang;}
    public JLabel getLblNgayHoanThanh(){return lblNgayHoanThanh;}
}
